"""Drawing a block: the chrome orch owns (title, layer chip, source, the Show numbers/Show text toggle, the anchor),
the states (invalid, misplaced, missing file, changed file, agent HTML off), the text alternative, and the
standalone document (docs/widgets.md, "Provenance and text alternative", "Rendering API")."""
from __future__ import annotations

import base64
import functools
import html
import re
from dataclasses import dataclass, replace
from pathlib import Path

from orch.widgets import artifacts, frames, registry
from orch.widgets.blocks import Block
from orch.widgets.validate import validate

try:
    from markupsafe import Markup
except ImportError:  # the CLI without the dashboard extra: plain strings are just as good there
    Markup = str  # type: ignore[assignment,misc]

STATIC = Path(__file__).resolve().parents[1] / "dashboard" / "static"
CSS_DIR = STATIC / "widgets"
# The frame's policy (the contract's "The frame"): nothing loads, nothing leaves; inline script and style only.
FRAME_CSP = ("default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; "
             "media-src data: blob:; font-src data:; connect-src 'none'; form-action 'none'; base-uri 'none'")
# The same as a response header (GET /w/…): `sandbox` gives the document an opaque origin, frame-ancestors keeps it
# inside the dashboard (neither works from a <meta>).
FRAME_CSP_HEADER = f"sandbox allow-scripts; {FRAME_CSP}; frame-ancestors 'self'"
NO_TEXT = "No text alternative given"
HTML_OFF = "Agent HTML is off in this workspace (the human turns it on with orch widget html on)"


@dataclass
class Ctx:
    """What a renderer may know: the ticket, the workspace (home, artifacts, config), the theme and whether agent
    HTML is on (`widgets.html` in the workspace config, backed by a signed human decision: Ctx.of)."""
    ticket: object = None
    ws: object = None
    theme: str = "system"
    html: bool = False
    standalone: bool = False  # a self-contained document: files are embedded as data: URIs, not linked as /a/…
    nonce: str = ""  # the frame's nonce from the host (GET /w/…?n=); empty: a fresh one per document

    @classmethod
    def of(cls, ws, ticket=None, theme: str | None = None) -> "Ctx":
        from orch.core import ledger
        cfg = getattr(ws, "config", None) or {}
        return cls(ticket=ticket, ws=ws, theme=theme or cfg.get("dashboard", {}).get("theme", "system"),
                   html=ledger.widgets_html_state(ws) == "on")

    @property
    def home(self) -> Path | None:
        return getattr(self.ws, "home", None)


def esc(value) -> str:
    return html.escape(str(value), quote=True)


def inline(text, ctx=None) -> str:
    """One line of Markdown (code, emphasis, links) as HTML, links by R24 and artifacts inert (types.scope); escaped
    text where the dashboard extra is missing."""
    try:
        from orch.dashboard.markdown import render_inline
    except ImportError:
        return esc(text)
    from orch.widgets.types import scope
    return render_inline(str(text), scope(ctx), page=getattr(getattr(ctx, "ticket", None), "is_page", False))


def _chip(block: Block, ctx: Ctx) -> str:
    if block.layer == "type":
        return "core"
    if block.layer == "widget":
        return f"agent HTML · {block.data['widget']}"
    return "agent HTML · one-off"


def note(role: str, word: str, text: str) -> str:
    """A state line: the word ("Warning", "Error", "Note") carries the meaning, the colour only repeats it."""
    return f'<p class="w-note w-note-{role}" role="note"><b>{esc(word)}:</b> {esc(text)}</p>'


def _where(block: Block) -> str:
    return f"{block.section or 'before the first section'}, line {block.line}"  # on a page the section is its path


def _as_code(block: Block, role: str, head: str, text: str) -> str:
    return (f'<div class="w w-{"invalid" if role == "err" else "misplaced"}" role="group" aria-label="{esc(head)}">'
            f'<p class="w-note w-note-{role}" role="note"><b>{esc(head)}</b> · {esc(_where(block))}: {esc(text)}</p>'
            f'<pre class="w-raw"><code>{esc(block.raw)}</code></pre></div>')


def text_of(block: Block, ctx: Ctx) -> str:
    """The text alternative: generated by a core type, else the caption (agent HTML sets its own in the frame)."""
    if block.layer == "type" and block.data["type"] in registry.core_types():
        return registry.core_types()[block.data["type"]].render_text(block, ctx)
    return frames.text(block, ctx) or (block.data or {}).get("caption") or NO_TEXT


def render_html(block: Block, ctx: Ctx, *, bare: bool = False) -> Markup:
    """The block as HTML for a page: the chrome around the body, or an error/warning state with the raw block.
    bare=True leaves out the chrome a host draws itself (title, chip, text alternative, source)."""
    return chrome(block, ctx, bare=bare)


def chrome(block: Block, ctx: Ctx, *, framed: bool = True, bare: bool = False) -> Markup:
    """`render_html`; with framed=False an agent-HTML block gets no frame placeholder, only its text alternative
    (what a frame hook without a renderer puts in its document); with bare=True no head, text alternative or
    source, only the states and the body (and a core type's caption)."""
    problems = validate(block, ctx.ticket, ws=ctx.ws)
    hard = [p for p in problems if p.level == "error" and p.code in ("widget-parse", "widget-schema")]
    if hard:
        return Markup(_as_code(block, "err", "Widget not shown", "; ".join(p.message for p in hard)))
    if any(p.code == "widget-place" for p in problems):
        return Markup(_as_code(block, "warn", "Shown as code", problems[0].message))
    data = block.data
    notes = [note("warn", "Drift", p.message) if p.code == "widget-drift" else
             note("err" if p.level == "error" else "warn", "Error" if p.level == "error" else "Warning", p.message)
             for p in problems if p.code in ("widget-digest", "widget-drift")]
    if getattr(ctx.ticket, "is_page", False) and data.get("type") == "checks":
        notes.append(note("neu", "Note", "A claim written on this page: not a gate, and not the ticket's verdict. "
                                        "What a ticket records is shown on the ticket"))
    if data.get("type") == "gates" and unverified_receipt(block, ctx):
        notes.append(note("warn", "Unverified", "no receipt recorded by orch backs this block (`orch task done --run` "
                                                "writes it): it was written by hand"))
    missing = any(p.level == "error" for p in problems)
    alt_label = "Show text"
    if block.layer == "type":
        mod = registry.core_types()[data["type"]]
        alt_label = "Show numbers" if getattr(mod, "ALT", "text") == "numbers" else "Show text"
        body = "" if missing else str(mod.render_html(block, ctx))
    elif not ctx.html:
        notes.append(note("neu", "Note", HTML_OFF + "; the text alternative is shown"))
        body = ""
    elif missing:
        body = ""
    else:
        if not frames.INSTALLED:
            notes.append(note("neu", "Note", "agent HTML renderer not installed; the text alternative is shown"))
        body = _frame_placeholder(block, ctx) if framed else ""
    kind = esc(data.get("type") or block.layer)
    head = (f'<span class="w-title">{esc(data["title"])}</span>' if data.get("title") else "") + \
        f'<span class="w-chip">{esc(_chip(block, ctx))}</span>'
    parts = [f'<figure class="w w-t-{kind}" id="w-{esc(block.key)}" data-layer="{"core" if block.layer == "type" else esc(block.layer)}">',
             "" if bare else f'<figcaption class="w-head">{head}</figcaption>', *notes]
    if body:
        parts.append(f'<div class="w-body">{body}</div>')
    if bare:
        if data.get("caption") and block.layer == "type":
            parts.append(f'<p class="w-caption">{esc(data["caption"])}</p>')
        return Markup("".join(parts) + "</figure>")
    shown = body and (block.layer == "type" or frames.INSTALLED)  # else the text is all there is: open it
    parts.append(f'<details class="w-alt"{"" if shown else " open"}><summary>{alt_label}</summary>'
                 f'<pre class="w-text">{esc(text_of(block, ctx))}</pre></details>')
    if data.get("source"):
        parts.append(f'<p class="w-source">Source: {esc(data["source"])}</p>')
    if data.get("caption") and block.layer == "type":
        parts.append(f'<p class="w-caption">{esc(data["caption"])}</p>')
    parts.append("</figure>")
    return Markup("".join(parts))


_RECEIPT_ID = re.compile(r"receipt-(t\d+)\Z", re.I)


def unverified_receipt(block: Block, ctx: Ctx) -> bool:
    """A `gates` block with the id `receipt-t<n>` (the one `orch task done --run` draws) that no receipt artifact entry
    of that task backs: widgets are agent-writable, so a pass-looking block could be typed by hand. It is backed when the
    task's newest receipt entry (written by orch alone) names the same steps with the same statuses. Page widgets and
    blocks with any other id are not judged."""
    m = _RECEIPT_ID.match(str((block.data or {}).get("id") or ""))
    meta = getattr(ctx.ticket, "meta", None)
    if not m or not isinstance(meta, dict) or getattr(ctx.ticket, "is_page", False):
        return False
    task = m.group(1).upper()
    runs = [e for e in (meta.get("artifacts") or []) if isinstance(e, dict) and e.get("kind") == "receipt"
            and str(e.get("task") or "").upper() == task and isinstance(e.get("run"), dict)]
    if not runs:
        return True
    shown = [(i.get("name"), i.get("status")) for i in (block.data.get("items") or []) if isinstance(i, dict)]
    steps = [(s.get("name"), s.get("status")) for s in (runs[-1]["run"].get("steps") or []) if isinstance(s, dict)]
    return shown != steps


def frame_path(ticket_id: str, block: Block) -> str:
    """Where a frame loads its block: /w/<ID>/<section>/<digest>. The route serves only the block of that section whose
    canonical JSON has that digest, so another block (another section, a reused id, a shifted index) never fills it."""
    from urllib.parse import quote
    return f"/w/{quote(str(ticket_id), safe='')}/{quote(block.section, safe='')}/{block.digest}"


def _frame_placeholder(block: Block, ctx: Ctx) -> str:
    """Where the host script puts `<iframe sandbox="allow-scripts" src=…>`; until then the frame hook's fallback."""
    import secrets
    tid = getattr(ctx.ticket, "id", "")
    height = block.data.get("height") or 160
    if block.layer == "widget":
        spec, _ = registry.template_version(ctx.home, block.data["widget"])
        height = block.data.get("height") or (spec or {}).get("min_height") or 160
    nonce = secrets.token_urlsafe(12)
    if getattr(ctx.ticket, "is_page", False):  # /wp/<addon>/<digest>?page=<id>: the page's text is read by its addon
        from urllib.parse import quote
        url = f"/wp/{quote(ctx.ticket.id.addon, safe='')}/{block.digest}?page={quote(str(tid), safe='')}&n={nonce}"
    else:
        url = f"{frame_path(tid, block)}?n={nonce}"
    return (f'<div class="w-frame" data-doc-url="{esc(url)}" data-nonce="{nonce}" '
            f'data-min-height="{int(height)}" data-title="{esc(block.data.get("title") or "Widget")}">'
            f'{frames.fallback(block, ctx)}</div>')


def render_text(block: Block, ctx: Ctx) -> str:
    """The block as plain text (`orch widget render --text`, `orch show --widgets`, a phone companion)."""
    problems = validate(block, ctx.ticket, ws=ctx.ws)
    if any(p.level == "error" and p.code not in ("widget-digest", "widget-drift") for p in problems):
        what = "shown as code" if problems[0].code == "widget-place" else "widget not shown"
        return f"[{what} · {_where(block)}: {'; '.join(p.message for p in problems)}]"
    data = block.data
    head = " · ".join(x for x in (data.get("title"), _chip(block, ctx)) if x)
    lines = [f"[{head}]", text_of(block, ctx)]
    lines += [f"{p.level}: {p.message}" for p in problems]
    if data.get("source"):
        lines.append(f"Source: {data['source']}")
    return "\n".join(lines)


def widget_css() -> str:
    """The widget stylesheets (static/widgets/*.css), core.css first."""
    files = sorted(CSS_DIR.glob("*.css"), key=lambda p: (p.name != "core.css", p.name))
    return "\n".join(p.read_text(encoding="utf-8") for p in files)


def css_names() -> list[str]:
    """The widget stylesheets as static paths (widgets/core.css, …), for a page that links them."""
    return [f"widgets/{p.name}" for p in sorted(CSS_DIR.glob("*.css"), key=lambda p: (p.name != "core.css", p.name))]


# The dashboard's fonts (static/fonts, app.css), weight ranges as there. A frame loads nothing, so they ride along
# as data: URIs (font-src data:); both together are about 45 KB, 60 KB as base64.
FONTS = (("Figtree", "300 900", "figtree-latin-wght.woff2"), ("Manrope", "200 800", "manrope-latin-wght.woff2"))


@functools.cache
def frame_tokens() -> str:
    """tokens.css with the dashboard's fonts inlined: the tokens CSS every frame document carries."""
    faces = "".join(
        f'@font-face{{font-family:"{name}";font-style:normal;font-weight:{weight};font-display:swap;'
        f'src:url(data:font/woff2;base64,{base64.b64encode((STATIC / "fonts" / file).read_bytes()).decode()}) '
        'format("woff2")}\n' for name, weight, file in FONTS)
    return faces + (STATIC / "tokens.css").read_text(encoding="utf-8")


def shell(body: str, ctx: Ctx, *, title: str = "Widget", head: str = "") -> str:
    """A self-contained document with the frame CSP, the theme tokens (and fonts) and the widget CSS inline."""
    tokens = frame_tokens()
    return ("<!doctype html>\n"
            f'<html lang="en" data-theme="{esc(ctx.theme)}"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width, initial-scale=1">'
            f'<meta http-equiv="Content-Security-Policy" content="{FRAME_CSP}">'  # a constant without "
            f"<title>{esc(title)}</title><style>{tokens}\n{widget_css()}</style>{head}</head>"
            f'<body class="w-doc">{body}</body></html>\n')


def render_document(block: Block, ctx: Ctx, *, chrome: bool = True) -> str:
    """One standalone HTML document per block (a phone companion, export, GET /w/…): core types are their HTML and
    CSS, no script; agent HTML is whatever the installed frame hook assembles (never any chrome). chrome=False: a
    core type without the title, chip, text alternative and source, for a host that draws those around the frame."""
    if block.layer in ("widget", "html") and ctx.html and not any(
            p.level == "error" for p in validate(block, ctx.ticket, ws=ctx.ws)):
        return frames.document(block, ctx)
    body = str(render_html(block, replace(ctx, standalone=True), bare=not chrome))
    if len(body) > artifacts.MAX_INLINED + 1024 * 1024:  # screens: up to 24 embedded images
        body = note("err", "Error", "widget not drawn: too many or too large images (8 MB at most in one widget)")
    return shell(body, ctx, title=(block.data or {}).get("title") or "Widget")


def annotate(raw: str, blocks: list[Block], ctx: Ctx) -> str:
    """The ticket file with each block's text alternative after its section (`orch show --widgets`)."""
    from orch.core import fences
    from orch.core.model import h2_title
    from orch.widgets.blocks import body_start
    lines = raw.split("\n")
    heads, fence = [], None
    for i in range(body_start(lines), len(lines)):
        was = fence
        fence, is_fence = fences.step(fence, lines[i])
        if was is None and not is_fence and h2_title(lines[i]) is not None:
            heads.append(i)
    ends: dict[int, list[str]] = {}
    for b in blocks:
        ends.setdefault(next((h for h in heads if h >= b.line), len(lines)), []).append(render_text(b, ctx))
    out = []
    for i in range(len(lines) + 1):
        for alt in ends.get(i, []):
            out += ["", *alt.split("\n"), ""]
        if i < len(lines):
            out.append(lines[i])
    return "\n".join(out)
