"""Canonical JSON (``cj``), the text rules, domain-labelled hashes, the gate hash, the event chain and the
bytes that get signed.

Specs: ``docs/architecture/orch-v2-ticket-format.md`` §5.3-§5.7 and §11, ``orch-relay/docs/protocol-v2.md`` §2.3.
Each module's docstring states its decisions. There is deliberately no general RFC 8785 serialiser here.
"""

from .hashing import (
    ARTIFACT_KINDS,
    CONTRACT,
    GATE_KEYS,
    GATES,
    HASH_V,
    LABELS,
    SUITE,
    ChainError,
    HashError,
    artifact_digest,
    check_chain,
    check_hash_v,
    event_head,
    event_line,
    format_hash,
    gate_hash,
    grant_secret_hash,
    host_signing_bytes,
    log_head,
    parse_event_line,
    parse_hash,
    people_hash,
    person_signing_bytes,
    policy_hash,
    question_hash,
    question_id,
    section_hash,
    signed_context,
    value_hash,
)
from .jcs import JcsError, dumps, loads_strict, validate
from .text import (
    UNICODE_VERSION,
    Suspect,
    TextError,
    check_text,
    is_normalized,
    nfc,
    normalize_text,
    show_invisible,
    suspicious,
)

__all__ = [
    "ARTIFACT_KINDS",
    "CONTRACT",
    "GATES",
    "GATE_KEYS",
    "HASH_V",
    "LABELS",
    "SUITE",
    "UNICODE_VERSION",
    "ChainError",
    "HashError",
    "JcsError",
    "Suspect",
    "TextError",
    "artifact_digest",
    "check_chain",
    "check_hash_v",
    "check_text",
    "dumps",
    "event_head",
    "event_line",
    "format_hash",
    "gate_hash",
    "grant_secret_hash",
    "host_signing_bytes",
    "is_normalized",
    "loads_strict",
    "log_head",
    "nfc",
    "normalize_text",
    "parse_event_line",
    "parse_hash",
    "people_hash",
    "person_signing_bytes",
    "policy_hash",
    "question_hash",
    "question_id",
    "section_hash",
    "show_invisible",
    "signed_context",
    "suspicious",
    "validate",
    "value_hash",
]
