"""Text rules for everything that is stored, signed or hashed (ticket-format §11.3).

What a string must be:

* UTF-8 encodable (Unicode scalar values only: a lone surrogate is refused), **NFC**, with **LF** line endings;
* free of C0 controls other than LF and TAB, DEL, C1 controls (U+0080..U+009F), bidi controls
  (U+202A..202E, U+2066..2069, U+200E, U+200F, U+061C) and code points unassigned in **Unicode 16.0**.

Nothing else is changed or refused: trailing spaces, a missing final newline and blank lines are kept (and hashed).

Two entry points with different jobs:

* :func:`normalize_text` is for text *entering* the store: CRLF and lone CR become LF, the result is put in NFC,
  then :func:`check_text` runs. The order matters: CR is a C0 control, so it must be converted before the check.
* :func:`check_text` is for everything else, in particular every hash and signature function: it **refuses** a
  string that breaks the rules and never normalises it (§5.6, "refuse, don't normalise").

Unicode version. §11.3 pins Unicode 16.0 for NFC and for "unassigned", whatever the Python runtime ships (3.11
has 14.0, 3.14 has 16.0). This module therefore never calls :mod:`unicodedata`: the assigned code points, the
canonical combining classes, the canonical decompositions and the primary composites of 16.0 are bundled in
``_unicode16`` (generated by ``tests/canon/gen_unicode16.py``), and NFC is implemented here (UAX #15: canonical
decomposition, canonical ordering, canonical composition, Hangul algorithmically). The tests compare this NFC
with the runtime's on every code point and on random strings whenever the runtime is Unicode 16.0.

Errors are :class:`TextError` (a ``ValueError``); no other exception type escapes for ``str`` input.
"""

from __future__ import annotations

import re
from bisect import bisect_right
from dataclasses import dataclass
from functools import lru_cache
from typing import Literal

from . import _unicode16 as _u

__all__ = [
    "BIDI_CONTROLS",
    "UNICODE_VERSION",
    "Suspect",
    "TextError",
    "check_text",
    "clean",
    "clean_line",
    "is_clean_text",
    "nfc",
    "normalize_text",
    "show_invisible",
    "suspicious",
]

UNICODE_VERSION = _u.UNICODE_VERSION

BIDI_CONTROLS = frozenset(
    [*range(0x202A, 0x202F), *range(0x2066, 0x206A), 0x200E, 0x200F, 0x061C],
)


class TextError(ValueError):
    """The string breaks the text rules of ticket-format §11.3."""


def _parse_ranges(blob: str, n: int) -> list[tuple[int, ...]]:
    out = []
    for line in blob.split("\n"):
        if line:
            parts = line.split()
            out.append(tuple(int(p, 16) if i < 2 else int(p) for i, p in enumerate(parts[:n])))
    return out


_ASSIGNED = _parse_ranges(_u.ASSIGNED_RANGES, 2)
_ASSIGNED_STARTS = [r[0] for r in _ASSIGNED]
_CF = _parse_ranges(_u.CF_RANGES, 2)
_CF_STARTS = [r[0] for r in _CF]
_CCC = _parse_ranges(_u.CCC_RANGES, 3)
_CCC_STARTS = [r[0] for r in _CCC]
_DECOMP: dict[int, tuple[int, ...]] = {}
for _line in _u.DECOMP.split("\n"):
    if _line:
        _cp, *_rest = (int(x, 16) for x in _line.split())
        _DECOMP[_cp] = tuple(_rest)
_COMPOSE: dict[tuple[int, ...], int] = {}
for _line in _u.COMPOSABLE.split("\n"):
    if _line:
        _cp = int(_line, 16)
        _COMPOSE[_DECOMP[_cp]] = _cp

_SBASE, _LBASE, _VBASE, _TBASE = 0xAC00, 0x1100, 0x1161, 0x11A7
_LCOUNT, _VCOUNT, _TCOUNT = 19, 21, 28
_NCOUNT = _VCOUNT * _TCOUNT
_SCOUNT = _LCOUNT * _NCOUNT


def _in_ranges(starts: list[int], ranges: list[tuple[int, ...]], cp: int) -> bool:
    i = bisect_right(starts, cp) - 1
    return i >= 0 and cp <= ranges[i][1]


def _assigned(cp: int) -> bool:
    return _in_ranges(_ASSIGNED_STARTS, _ASSIGNED, cp)


@lru_cache(maxsize=4096)
def _ccc(cp: int) -> int:
    i = bisect_right(_CCC_STARTS, cp) - 1
    return _CCC[i][2] if i >= 0 and cp <= _CCC[i][1] else 0


@lru_cache(maxsize=4096)
def _full_decomp(cp: int) -> tuple[int, ...]:
    if _SBASE <= cp < _SBASE + _SCOUNT:
        s = cp - _SBASE
        out = [_LBASE + s // _NCOUNT, _VBASE + (s % _NCOUNT) // _TCOUNT]
        if s % _TCOUNT:
            out.append(_TBASE + s % _TCOUNT)
        return tuple(out)
    d = _DECOMP.get(cp)
    if d is None:
        return (cp,)
    return tuple(x for part in d for x in _full_decomp(part))


def _compose_pair(a: int, b: int) -> int | None:
    if _LBASE <= a < _LBASE + _LCOUNT and _VBASE <= b < _VBASE + _VCOUNT:
        return _SBASE + ((a - _LBASE) * _VCOUNT + (b - _VBASE)) * _TCOUNT
    if _SBASE <= a < _SBASE + _SCOUNT and (a - _SBASE) % _TCOUNT == 0 and _TBASE < b < _TBASE + _TCOUNT:
        return a + (b - _TBASE)
    return _COMPOSE.get((a, b))


def nfc(text: str) -> str:
    """Unicode 16.0 NFC of ``text`` (independent of the runtime's Unicode version). Does not check the text rules.

    Raises :class:`TextError` for a non-``str`` argument."""
    if not isinstance(text, str):
        raise TextError(f"text must be str, not {type(text).__name__}")
    if text.isascii():
        return text
    cps: list[int] = []
    for ch in text:
        cps.extend(_full_decomp(ord(ch)))
    # canonical ordering: stable sort of each run of non-starters by combining class
    i, n = 0, len(cps)
    while i < n:
        if _ccc(cps[i]) == 0:
            i += 1
            continue
        j = i
        while j < n and _ccc(cps[j]) != 0:
            j += 1
        cps[i:j] = sorted(cps[i:j], key=_ccc)
        i = j
    # canonical composition
    out: list[int] = []
    starter = -1  # index in out of the last starter that can still absorb characters
    last_class = 0
    for cp in cps:
        cls = _ccc(cp)
        if starter >= 0:
            comp = _compose_pair(out[starter], cp)
            if comp is not None and (last_class < cls or last_class == 0):
                out[starter] = comp
                continue
        if cls == 0:
            starter = len(out)
        last_class = cls
        out.append(cp)
    return "".join(map(chr, out))


_ASCII_BAD = re.compile(r"[\x00-\x08\x0b-\x1f\x7f]")

# Non-Cf characters F1 §5.7/§11.3 also show: U+034F, U+115F, U+1160, U+2028, U+2029, U+3164, U+FFA0,
# U+FE00..FE0F and U+E0100..E01EF. Together with every Cf character they are "invisible"; the decision (an
# explicit list, not Default_Ignorable_Code_Point) is F1's.
_EXTRA_INVISIBLE = frozenset(
    [0x034F, 0x115F, 0x1160, 0x2028, 0x2029, 0x3164, 0xFFA0, *range(0xFE00, 0xFE10), *range(0xE0100, 0xE01F0)]
)


def _first_not_nfc(text: str) -> int:
    n = nfc(text)
    i = 0
    for a, b in zip(text, n, strict=False):
        if a != b:
            break
        i += 1
    return i


def _check(text: str, one_line: bool, known_nfc: bool) -> str:
    if not isinstance(text, str):
        raise TextError(f"text must be str, not {type(text).__name__}")
    if text.isascii():
        m = _ASCII_BAD.search(text)
        if m:
            raise TextError(f"control character U+{ord(m.group()):04X} at index {m.start()}")
    else:
        ok: set[str] = set()  # characters already accepted; the scan stays in text order
        for i, ch in enumerate(text):
            if ch in ok:
                continue
            cp = ord(ch)
            if 0xD800 <= cp <= 0xDFFF:
                raise TextError(f"lone surrogate at index {i}")
            if (cp < 0x20 and ch not in "\n\t") or 0x7F <= cp <= 0x9F:
                raise TextError(f"control character U+{cp:04X} at index {i}")
            if cp in BIDI_CONTROLS:
                raise TextError(f"bidi control U+{cp:04X} at index {i}")
            if not _assigned(cp):
                raise TextError(f"code point U+{cp:04X} at index {i} is unassigned in Unicode {UNICODE_VERSION}")
            ok.add(ch)
        if not known_nfc and nfc(text) != text:
            raise TextError(f"text is not in NFC (first difference at index {_first_not_nfc(text)})")
    if one_line and "\n" in text:
        raise TextError(f"line feed at index {text.index(chr(10))} in a one-line field")
    return text


def check_text(text: str, *, one_line: bool = False) -> str:
    """Return ``text`` unchanged if it follows §11.3, else raise :class:`TextError`. Never normalises.

    The scan is in text order, so the error names the first offending ``index`` (a code point index, not a byte
    offset). ``one_line=True`` additionally refuses LF (titles, labels, names, option labels, reasons).
    """
    return _check(text, one_line, False)


def normalize_text(text: str, *, one_line: bool = False) -> str:
    """For text entering the store: CRLF and lone CR become LF, then NFC (once), then the checks of §11.3.

    Idempotent. Raises :class:`TextError` when the normalised result still breaks the rules (controls, bidi
    controls, unassigned code points, lone surrogates); such text is refused, not repaired.
    """
    if not isinstance(text, str):
        raise TextError(f"text must be str, not {type(text).__name__}")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    return _check(nfc(text), one_line, True)


def is_clean_text(text: str, *, one_line: bool = False) -> bool:
    """True iff :func:`check_text` accepts ``text`` (all of §11.3, not just NFC), so normalising it is a no-op."""
    try:
        check_text(text, one_line=one_line)
    except TextError:
        return False
    return True


@dataclass(frozen=True, slots=True)
class Suspect:
    """One character an approval prompt must treat specially (:func:`suspicious`).

    ``index`` is a code point index into the ``str`` (not a UTF-8 offset)."""

    index: int
    codepoint: int
    kind: Literal["bidi", "invisible"]


def suspicious(text: str) -> list[Suspect]:
    """Characters of already-valid text that an approval prompt must refuse or show (ticket-format §5.7, §11.3).

    ``kind`` is ``"bidi"`` (the approval is refused, ``gate.suspicious_text``; bidi controls cannot enter the store,
    so this is defence in depth) or ``"invisible"``: every General_Category Cf character (U+200B..200D, U+2060,
    U+FEFF, tag characters, soft hyphen, ...) and F1's named non-Cf look-alikes (U+034F, U+115F, U+1160, U+2028,
    U+2029, U+3164, U+FFA0, U+FE00..FE0F, U+E0100..E01EF). Other characters are kept and not flagged (private use,
    other spaces). Returns an empty list when there is nothing to flag.
    """
    if not isinstance(text, str):
        raise TextError(f"text must be str, not {type(text).__name__}")
    out = []
    for i, ch in enumerate(text):
        cp = ord(ch)
        if cp in BIDI_CONTROLS:
            out.append(Suspect(i, cp, "bidi"))
        elif cp in _EXTRA_INVISIBLE or _in_ranges(_CF_STARTS, _CF, cp):
            out.append(Suspect(i, cp, "invisible"))
    return out


_LANGLE = "\u27e8"


def show_invisible(text: str) -> str:
    """``text`` with every :func:`suspicious` character replaced by a visible ``\u27e8U+XXXX\u27e9`` marker.

    A literal ``\u27e8`` in the text is itself shown as ``\u27e8U+27E8\u27e9``, so no text can forge a marker: every
    ``\u27e8`` in the output starts a real marker.
    """
    flagged = {s.index for s in suspicious(text)}
    return "".join(
        f"{_LANGLE}U+{ord(ch):04X}\u27e9" if i in flagged or ch == _LANGLE else ch for i, ch in enumerate(text)
    )


def clean(text: str) -> str:
    """The one escaping step for untrusted text that is echoed to a person: invisible and suspicious
    characters become ``\u27e8U+XXXX\u27e9`` markers (:func:`show_invisible`), and C0/C1 controls, ESC
    included, are escaped. Newline stays."""
    out = []
    for ch in show_invisible(text):
        o = ord(ch)
        if ch != "\n" and (o < 0x20 or 0x7F <= o <= 0x9F):
            out.append(f"\u27e8U+{o:04X}\u27e9")
        else:
            out.append(ch)
    return "".join(out)


def clean_line(text: str) -> str:
    """:func:`clean`, on one line, with the ``\u00b7`` field separator of error lines made visible."""
    return clean(" ".join(text.split())).replace("\u00b7", "\u27e8U+00B7\u27e9")
