import pytest

from orch.config.load import DEFAULTS, deep_merge
from orch.errors import ValidationError
from orch.instructions.blocks import BEGIN, END, apply_block, has_block, wrap
from orch.instructions.render import (agents_block, claude_block, commit_example, copilot_block, example_key,
                                      rules_file)


def cfg(**over):
    return deep_merge(DEFAULTS, {"customer": "acme", **over})


def test_apply_block_creates_with_stub():
    out = apply_block(None, wrap("hello"), stub="## Customer notes")
    assert out.startswith(BEGIN) and "hello" in out and out.rstrip().endswith("## Customer notes")


def test_apply_block_appends_to_file_without_markers():
    existing = "# My project\n\nKeep this text.\n"
    out = apply_block(existing, wrap("rules"))
    assert out.startswith(existing)  # customer content stays first and unchanged
    assert out.rstrip("\n").endswith(END) and has_block(out) and not has_block(existing)


def test_apply_block_replaces_only_inside_markers():
    first = apply_block("intro\n", wrap("v1"))
    edited = first + "\n## Notes\n\nmine\n"
    second = apply_block(edited, wrap("v2"))
    assert "v2" in second and "v1" not in second
    assert second.endswith("## Notes\n\nmine\n") and "intro" in second
    assert apply_block(second, wrap("v2")) == second  # idempotent


def test_apply_block_keeps_crlf_line_endings():
    out = apply_block("a\r\nb\r\n", wrap("x"))
    assert out == "a\r\nb\r\n\r\n" + wrap("x").replace("\n", "\r\n") + "\r\n"
    assert "\n" not in out.replace("\r\n", "")  # no bare LF anywhere
    assert apply_block(out, wrap("x")) == out  # idempotent
    updated = apply_block(out, wrap("y"))
    assert updated.startswith("a\r\nb\r\n") and "y" in updated and "\n" not in updated.replace("\r\n", "")


def test_apply_block_keeps_lf_files_lf():
    out = apply_block("a\nb\n", wrap("x"))
    assert "\r" not in out


@pytest.mark.parametrize("broken", [
    f"{BEGIN}\nx\n{BEGIN}\ny\n{END}\n",
    f"{END}\nx\n{BEGIN}\n",
    f"{BEGIN}\nno end\n",
])
def test_apply_block_refuses_broken_markers(broken):
    with pytest.raises(ValidationError):
        apply_block(broken, wrap("x"))


def test_example_key_and_commit_example():
    assert example_key(cfg()) == "L-0042"
    c = cfg(external_trackers=[{"prefix": "ABC", "pattern": "ABC-\\d+", "url": "u/{key}"}])
    assert example_key(c) == "ABC-123"
    ex = commit_example(c)
    assert ex.splitlines()[0] == "ABC-123 Add nightly config backup job"
    assert "What: " in ex and "Why:  " in ex and "Risk: " in ex
    assert "Rollback:" in commit_example(cfg(commit={"rollback": True}))


def test_agents_block_defaults():
    text = agents_block(cfg())
    assert text.startswith(BEGIN) and text.rstrip().endswith(END)
    assert "You do not commit" in text and "You do not push" in text and "You do not open PRs" in text
    assert "Co-Authored-By" in text and "L-0042 Add nightly config backup job" in text
    assert "What / Why / Risk / Verification" in text


def test_agents_block_follows_policy():
    text = agents_block(cfg(git={"review_term": "MR", "agent_may": {"commit": True, "push": True, "open_review": True}},
                            commit={"rollback": True, "forbid_attribution": False}))
    assert "You may commit" in text and "You may push" in text and "You may open a draft MR" in text
    assert "Rollback" in text and "Co-Authored-By" not in text


def test_claude_and_copilot_blocks():
    claude = claude_block(cfg())
    assert "\n@orchestrator/AGENTS.orch.md\n" in claude and "Working rules" not in claude  # import, not a copy
    cop = copilot_block(cfg())
    assert "orchestrator/AGENTS.orch.md" in cop and "commit-msg" in cop and "orch check" in cop


def test_rules_file_is_unmarked_full_rules():
    text = rules_file(cfg())
    assert BEGIN not in text and "## Working rules (orch)" in text and "Generated by `orch instructions sync`" in text
