import json
import shlex
import shutil
import subprocess

import pytest

from orch.cli import run
from orch.hooks.commit_msg import check_message, clean_message
from orch.hooks.install import hook_script, hook_state, install_hooks, is_orch_hook

GOOD_BODY = "\n\nWhat: add it\nWhy:  needed\nRisk: low\n"


def test_valid_message_for_xs_ticket(ws, put):
    tid = put("in-progress", size="xs")
    assert check_message(ws, f"{tid} Add nightly job{GOOD_BODY}") == []


def test_body_lines_required(ws, put):
    tid = put("in-progress", size="xs")
    problems = check_message(ws, f"{tid} Add nightly job\n\nWhat: add it\n")
    assert any("'Why:'" in p for p in problems) and any("'Risk:'" in p for p in problems)


def test_bad_subject_and_unknown_ticket(ws, put):
    assert any("subject must match" in p for p in check_message(ws, f"fix stuff{GOOD_BODY}"))
    assert any("no ticket L-0099" in p for p in check_message(ws, f"L-0099 Add thing{GOOD_BODY}"))


def test_plan_gate_required_for_non_xs(ws, put):
    tid = put("in-progress", size="m")
    assert any("plan is not approved" in p for p in check_message(ws, f"{tid} Add thing{GOOD_BODY}"))


@pytest.mark.parametrize("line", [
    "Co-Authored-By: Claude Opus <noreply@anthropic.com>",
    "co-authored-by: GitHub Copilot <copilot@github.com>",
    "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
    "Generated by Codex",
    "Co-Authored-By: ChatGPT <x@y>",
    "Assisted-by: Claude",
    "Reviewed-by: Cursor Agent <agent@cursor.sh>",
])
def test_attribution_rejected(ws, put, line):
    tid = put("in-progress", size="xs")
    assert any("attribution" in p for p in check_message(ws, f"{tid} Add thing{GOOD_BODY}\n{line}\n"))


def test_human_trailers_allowed(ws, put):
    tid = put("in-progress", size="xs")
    assert check_message(ws, f"{tid} Add thing{GOOD_BODY}\nReviewed-by: Anna Muster <anna@example.com>\n") == []


def test_attribution_allowed_when_configured(configure, put):
    ws = configure(commit={"forbid_attribution": False})
    tid = put("in-progress", size="xs")
    assert check_message(ws, f"{tid} Add thing{GOOD_BODY}\nCo-Authored-By: Claude <x@y>\n") == []


def test_comments_scissors_and_crlf_ignored(ws, put):
    tid = put("in-progress", size="xs")
    text = (f"{tid} Add thing\r\n\r\nWhat: a\r\nWhy: b\r\nRisk: c\r\n# Please enter the commit message\r\n"
            "# ------------------------ >8 ------------------------\r\n"
            "diff --git a/x b/x\r\n+Co-Authored-By: Claude\r\n")
    assert clean_message(text).endswith("Risk: c")
    assert check_message(ws, text) == []


def test_merge_and_revert_skip_format_but_not_attribution(ws):
    assert check_message(ws, "Merge branch 'main' into feature/x\n") == []
    assert check_message(ws, "Revert \"L-0001 Add thing\"\n") == []
    assert check_message(ws, "Merge branch 'x'\n\nCo-Authored-By: Claude <a@b>\n") != []


def test_external_key_resolves(configure, put):
    ws = configure(external_trackers=[{"prefix": "ABC", "pattern": "ABC-\\d+", "url": "u/{key}"}])
    put("in-progress", size="xs", external=[{"key": "ABC-123", "url": "u/ABC-123"}])
    assert check_message(ws, f"ABC-123 Add thing{GOOD_BODY}") == []


def test_empty_message(ws):
    assert check_message(ws, "# only comments\n") == ["the commit message is empty"]


def _git(repo, *args):
    return subprocess.run(["git", "-C", str(repo), "-c", "user.name=t", "-c", "user.email=t@t", *args],
                          capture_output=True, text=True)


needs_git = pytest.mark.skipif(shutil.which("git") is None, reason="git not installed")
needs_sh = pytest.mark.skipif(shutil.which("sh") is None, reason="sh not installed")


def _hooks_dir(repo):
    out = _git(repo, "rev-parse", "--git-path", "hooks").stdout.strip()
    return (repo / out).resolve()


def _new_repo(ws_root, name):
    repo = ws_root / name
    repo.mkdir()
    assert _git(repo, "init", "-q").returncode == 0
    return repo


def _rows(ws, **kw):
    return {p.name: a for p, a in install_hooks(ws, **kw)}


def test_git_tests_ignore_the_users_global_config():
    import os
    assert os.environ.get("GIT_CONFIG_NOSYSTEM") == "1"
    assert os.environ.get("GIT_CONFIG_GLOBAL")
    if shutil.which("git"):
        assert subprocess.run(["git", "config", "--global", "--list"], capture_output=True, text=True).stdout == ""


@needs_git
def test_install_hooks_into_repo_hooks_dir(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    ws = configure(git={"repos": {"hub": {}, "missing": {}}})
    got = _rows(ws)
    assert got["hub"] == "installed"
    assert got["missing"].startswith("skipped: not a git repository")
    script = _hooks_dir(repo) / "commit-msg"
    text = script.read_text(encoding="utf-8")
    assert text.startswith("#!/bin/sh\n") and "ORCH_HOME=" in text and "hook commit-msg" in text
    assert script.stat().st_mode & 0o111
    assert _git(repo, "config", "--get", "core.hooksPath").returncode == 1  # never set
    assert not (ws.root / ".githooks").exists()
    assert _rows(ws)["hub"] == "unchanged"
    script.write_text(text.replace("ORCH_HOME=", "ORCH_HOME_OLD=x\nORCH_HOME="), encoding="utf-8")
    assert _rows(ws)["hub"] == "updated"
    assert script.read_text(encoding="utf-8") == text


@needs_git
@needs_sh
def test_install_hooks_keeps_existing_pre_commit_working(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    marker = ws_root / "pre-commit-ran"
    pre_commit = _hooks_dir(repo) / "pre-commit"
    pre_commit.parent.mkdir(parents=True, exist_ok=True)
    pre_commit.write_text(f"#!/bin/sh\ntouch {shlex.quote(str(marker))}\n", encoding="utf-8")
    pre_commit.chmod(0o755)
    ws = configure(git={"repos": {"hub": {}}})
    assert _rows(ws)["hub"] == "installed"
    _git(repo, "commit", "--allow-empty", "-q", "-m", "anything")
    assert marker.exists()  # the repo's own pre-commit hook still runs


@needs_git
@needs_sh
def test_install_hooks_skips_then_chains_existing_commit_msg(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    hooks = _hooks_dir(repo)
    hooks.mkdir(parents=True, exist_ok=True)
    marker = ws_root / "old-hook-ran"
    old = f"#!/bin/sh\necho \"$1\" > {shlex.quote(str(marker))}\n"
    (hooks / "commit-msg").write_text(old, encoding="utf-8")
    (hooks / "commit-msg").chmod(0o755)
    ws = configure(git={"repos": {"hub": {}}})
    got = _rows(ws)["hub"]
    assert got.startswith("skipped: a commit-msg hook already exists") and "--force" in got
    assert (hooks / "commit-msg").read_text(encoding="utf-8") == old
    got = _rows(ws, force=True)["hub"]
    assert got.startswith("installed") and "commit-msg.pre-orch" in got
    assert (hooks / "commit-msg.pre-orch").read_text(encoding="utf-8") == old
    assert "hook commit-msg" in (hooks / "commit-msg").read_text(encoding="utf-8")
    assert _rows(ws, force=True)["hub"] == "unchanged"
    # the chained hook runs after the orch check passes (orch is faked to accept everything)
    fake_bin = ws_root / "bin"
    fake_bin.mkdir()
    (fake_bin / "orch").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    (fake_bin / "orch").chmod(0o755)
    msg = ws_root / "MSG"
    msg.write_text("x\n", encoding="utf-8")
    r = subprocess.run(["sh", str(hooks / "commit-msg"), str(msg)], capture_output=True, text=True,
                       env={"PATH": f"{fake_bin}:/usr/bin:/bin"})
    assert r.returncode == 0, r.stderr
    assert marker.read_text(encoding="utf-8").strip() == str(msg)
    # and does not run when orch rejects the message
    marker.unlink()
    (fake_bin / "orch").write_text("#!/bin/sh\nexit 1\n", encoding="utf-8")
    r = subprocess.run(["sh", str(hooks / "commit-msg"), str(msg)], capture_output=True, text=True,
                       env={"PATH": f"{fake_bin}:/usr/bin:/bin"})
    assert r.returncode == 1 and not marker.exists()


def _common_hooks(repo):
    out = _git(repo, "rev-parse", "--git-common-dir").stdout.strip()
    return (repo / out).resolve() / "hooks"


def _fake_orch(ws_root, exit_code):
    fake_bin = ws_root / "bin"
    fake_bin.mkdir(exist_ok=True)
    (fake_bin / "orch").write_text(f"#!/bin/sh\necho \"$@\" >> {shlex.quote(str(ws_root / 'orch-calls'))}\nexit {exit_code}\n",
                                   encoding="utf-8")
    (fake_bin / "orch").chmod(0o755)
    return {"PATH": f"{fake_bin}:/usr/bin:/bin"}


@needs_git
def test_hooks_path_without_commit_msg_gets_one_that_runs_the_local_check(configure, ws_root):
    """#18: a repo with its own core.hooksPath gets a tracked commit-msg there that runs this clone's orch hook."""
    repo = _new_repo(ws_root, "hub")
    _git(repo, "config", "core.hooksPath", "scripts/git-hooks")
    (repo / "scripts" / "git-hooks").mkdir(parents=True)
    (repo / "scripts" / "git-hooks" / "pre-commit").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    ws = configure(git={"repos": {"hub": {}}})
    got = _rows(ws)["hub"]
    tracked = repo / "scripts" / "git-hooks" / "commit-msg"
    assert got.startswith("installed") and "scripts/git-hooks/commit-msg" in got and "commit" in got.split(";", 1)[1]
    text = tracked.read_text(encoding="utf-8")
    assert text.startswith("#!/bin/sh\n") and "# >>> orch commit-msg check >>>" in text
    assert str(ws_root) not in text and "ORCH_HOME" not in text  # nothing machine-specific in a tracked file
    assert tracked.stat().st_mode & 0o111
    assert is_orch_hook((_common_hooks(repo) / "commit-msg").read_text(encoding="utf-8"))  # the local, untracked hook
    assert _git(repo, "config", "--get", "core.hooksPath").stdout.strip() == "scripts/git-hooks"  # untouched
    assert hook_state(repo) == "installed"


@needs_git
@needs_sh
def test_hooks_path_commit_msg_gets_the_call_once(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    custom = repo / "custom hooks"  # inside the worktree, configured by absolute path
    custom.mkdir()
    marker = ws_root / "theirs-ran"
    theirs = f"#!/usr/bin/env bash\n# their own check\necho \"$1\" > {shlex.quote(str(marker))}\nexit 0\n"
    (custom / "commit-msg").write_text(theirs, encoding="utf-8")
    (custom / "commit-msg").chmod(0o755)
    _git(repo, "config", "core.hooksPath", str(custom))
    ws = configure(git={"repos": {"hub": {}}})
    got = _rows(ws)["hub"]
    assert got.startswith("installed") and "added" in got and "commit" in got
    text = (custom / "commit-msg").read_text(encoding="utf-8")
    assert text.startswith("#!/usr/bin/env bash\n# >>> orch commit-msg check >>>")  # runs before their exit 0
    assert text.endswith(theirs.split("\n", 1)[1])  # their script is kept as it was
    again = _rows(ws)["hub"]
    assert again.startswith("unchanged") and "commit" in again  # idempotent, and still says where the file is
    assert (custom / "commit-msg").read_text(encoding="utf-8") == text
    assert text.count("# >>> orch commit-msg check >>>") == 1
    assert (custom / "commit-msg").stat().st_mode & 0o777 == 0o755  # permissions kept
    assert not (custom / "commit-msg.pre-orch").exists()
    # a commit runs the orch check first, then their hook; a rejected message stops it
    env = _fake_orch(ws_root, 0)
    msg = ws_root / "MSG"
    msg.write_text("x\n", encoding="utf-8")
    r = subprocess.run(["sh", str(custom / "commit-msg"), str(msg)], capture_output=True, text=True, cwd=repo, env=env)
    assert r.returncode == 0, r.stderr
    assert "hook commit-msg" in (ws_root / "orch-calls").read_text(encoding="utf-8") and marker.exists()
    marker.unlink()
    env = _fake_orch(ws_root, 1)
    r = subprocess.run(["sh", str(custom / "commit-msg"), str(msg)], capture_output=True, text=True, cwd=repo, env=env)
    assert r.returncode == 1 and not marker.exists()


@needs_git
@needs_sh
def test_hooks_path_hook_does_nothing_in_a_clone_without_orch(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    _git(repo, "config", "core.hooksPath", ".githooks")
    ws = configure(git={"repos": {"hub": {}}})
    _rows(ws)
    (_common_hooks(repo) / "commit-msg").unlink()  # e.g. a teammate's fresh clone: only the tracked file
    assert hook_state(repo) == "missing"  # doctor: run `orch hooks install` here
    msg = ws_root / "MSG"
    msg.write_text("anything\n", encoding="utf-8")
    r = subprocess.run(["sh", str(repo / ".githooks" / "commit-msg"), str(msg)], capture_output=True, text=True,
                       cwd=repo, env={"PATH": "/usr/bin:/bin"})
    assert r.returncode == 0, r.stderr


@needs_git
def test_hooks_path_commit_msg_that_is_not_a_shell_script_is_left_alone(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    custom = repo / "custom"
    custom.mkdir()
    py = "#!/usr/bin/env python3\nimport sys\n"
    (custom / "commit-msg").write_text(py, encoding="utf-8")
    _git(repo, "config", "core.hooksPath", str(custom))
    ws = configure(git={"repos": {"hub": {}}})
    got = _rows(ws, force=True)["hub"]
    assert got.startswith("skipped:") and "orch hook commit-msg" in got
    assert (custom / "commit-msg").read_text(encoding="utf-8") == py
    assert hook_state(repo) == "foreign"


_SKIP_BY_HAND = "add `orch hook commit-msg \"$1\"` to that hook manually"


@needs_git
def test_global_hooks_path_is_never_edited(configure, ws_root):
    """A core.hooksPath from the user's global config serves every repo: never write there, never say "commit it"."""
    repo = _new_repo(ws_root, "hub")
    shared = ws_root / "global-hooks"
    shared.mkdir()
    (shared / "commit-msg").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    assert _git(repo, "config", "--global", "core.hooksPath", str(shared)).returncode == 0
    ws = configure(git={"repos": {"hub": {}}})
    got = _rows(ws, force=True)["hub"]
    assert got == f"skipped: core.hooksPath is set to {shared}; {_SKIP_BY_HAND}"
    assert (shared / "commit-msg").read_text(encoding="utf-8") == "#!/bin/sh\nexit 0\n"
    assert sorted(x.name for x in shared.iterdir()) == ["commit-msg"]
    assert not (_common_hooks(repo) / "commit-msg").exists()


@needs_git
def test_local_hooks_path_outside_the_worktree_is_skipped(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    outside = ws_root / "elsewhere"
    _git(repo, "config", "core.hooksPath", str(outside))
    ws = configure(git={"repos": {"hub": {}}})
    assert _rows(ws, force=True)["hub"] == f"skipped: core.hooksPath is set to {outside}; {_SKIP_BY_HAND}"
    assert not outside.exists()


@needs_git
def test_ignored_hooks_path_is_skipped_with_guidance(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    (repo / ".gitignore").write_text("gen-hooks/\n", encoding="utf-8")
    (repo / "gen-hooks").mkdir()
    _git(repo, "config", "core.hooksPath", "gen-hooks")
    ws = configure(git={"repos": {"hub": {}}})
    got = _rows(ws)["hub"]
    assert got.startswith("skipped:") and "ignored by git" in got and "commit it" not in got
    assert list((repo / "gen-hooks").iterdir()) == []


@needs_git
@needs_sh
def test_husky_hooks_path_gets_the_call_in_the_tracked_husky_hook(configure, ws_root):
    """husky v9: core.hooksPath=.husky/_ is generated and ignored; the hooks people commit are .husky/<name>."""
    repo = _new_repo(ws_root, "hub")
    husky = repo / ".husky"
    (husky / "_").mkdir(parents=True)
    (husky / "_" / ".gitignore").write_text("*\n", encoding="utf-8")
    wrapper = '#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n'
    (husky / "_" / "commit-msg").write_text(wrapper, encoding="utf-8")
    theirs = "npx --no -- commitlint --edit $1\n"  # husky hooks have no shebang
    (husky / "commit-msg").write_text(theirs, encoding="utf-8")
    _git(repo, "config", "core.hooksPath", ".husky/_")
    ws = configure(git={"repos": {"hub": {}}})
    got = _rows(ws)["hub"]
    assert got.startswith("installed") and ".husky/commit-msg" in got and "commit it" in got
    assert (husky / "_" / "commit-msg").read_text(encoding="utf-8") == wrapper  # the generated file is left alone
    text = (husky / "commit-msg").read_text(encoding="utf-8")
    assert text.startswith("# >>> orch commit-msg check >>>") and text.endswith(theirs)
    assert hook_state(repo) == "installed"
    assert _rows(ws)["hub"].startswith("unchanged")
    assert (husky / "commit-msg").read_text(encoding="utf-8") == text


@needs_git
def test_husky_without_a_commit_msg_hook_gets_one(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    (repo / ".husky" / "_").mkdir(parents=True)
    (repo / ".husky" / "_" / ".gitignore").write_text("*\n", encoding="utf-8")
    _git(repo, "config", "core.hooksPath", ".husky/_")
    ws = configure(git={"repos": {"hub": {}}})
    assert _rows(ws)["hub"].startswith("installed")
    assert "# >>> orch commit-msg check >>>" in (repo / ".husky" / "commit-msg").read_text(encoding="utf-8")
    assert not (repo / ".husky" / "_" / "commit-msg").exists()


@needs_git
def test_doctor_reports_hooks_path_repo_as_covered(configure, ws_root):
    from orch.onboarding import doctor
    repo = _new_repo(ws_root, "hub")
    _git(repo, "config", "core.hooksPath", "hooks")
    ws = configure(git={"repos": {"hub": {}}})
    assert {c.code: c.ok for c in doctor(ws_root)}["hooks"] is False
    _rows(ws)
    assert {c.code: c.ok for c in doctor(ws_root)}["hooks"] is True


@needs_git
def test_install_hooks_refuses_to_clobber_pre_orch(configure, ws_root):
    repo = _new_repo(ws_root, "hub")
    hooks = _hooks_dir(repo)
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "commit-msg").write_text("#!/bin/sh\necho new\n", encoding="utf-8")
    (hooks / "commit-msg.pre-orch").write_text("#!/bin/sh\necho old\n", encoding="utf-8")
    ws = configure(git={"repos": {"hub": {}}})
    got = _rows(ws, force=True)["hub"]
    assert got.startswith("skipped:") and "commit-msg.pre-orch" in got
    assert (hooks / "commit-msg").read_text(encoding="utf-8") == "#!/bin/sh\necho new\n"


@needs_git
def test_install_hooks_reports_write_failure(configure, ws_root, monkeypatch):
    import orch.hooks.install as install_mod
    _new_repo(ws_root, "hub")
    ws = configure(git={"repos": {"hub": {}}})

    def boom(path, text):
        raise PermissionError("read-only")

    monkeypatch.setattr(install_mod, "atomic_write_text", boom)
    got = _rows(ws)["hub"]
    assert got.startswith("failed:") and "read-only" in got


@needs_git
def test_install_hooks_failed_chain_restores_customer_hook(configure, ws_root, monkeypatch):
    import orch.hooks.install as install_mod
    repo = _new_repo(ws_root, "hub")
    hooks = _hooks_dir(repo)
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "commit-msg").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    ws = configure(git={"repos": {"hub": {}}})

    def boom(path, text):
        raise PermissionError("read-only")

    monkeypatch.setattr(install_mod, "atomic_write_text", boom)
    assert _rows(ws, force=True)["hub"].startswith("failed:")
    assert (hooks / "commit-msg").read_text(encoding="utf-8") == "#!/bin/sh\nexit 0\n"
    assert not (hooks / "commit-msg.pre-orch").exists()


def test_install_hooks_needs_repos(ws):
    from orch.errors import UsageError
    with pytest.raises(UsageError):
        install_hooks(ws)


@needs_sh
def test_hook_script_falls_back_to_baked_path(ws, tmp_path):
    # directory name with a space and a single quote, to exercise _sq() quoting on both paths
    fake_dir = tmp_path / "it's here"
    fake_dir.mkdir()
    fake = fake_dir / "orch"
    record = fake_dir / "record.txt"
    fake.write_text(
        "#!/bin/sh\n"
        f"echo \"$@\" > {shlex.quote(str(record))}\n"
        f"echo \"ORCH_HOME=$ORCH_HOME\" >> {shlex.quote(str(record))}\n"
    )
    fake.chmod(0o755)

    script = fake_dir / "commit-msg"
    script.write_text(hook_script(ws, str(fake)))
    script.chmod(0o755)

    msgfile = tmp_path / "MSG"
    result = subprocess.run(["sh", str(script), str(msgfile)], capture_output=True, text=True,
                            env={"PATH": "/usr/bin:/bin"})
    assert result.returncode == 0, result.stderr
    lines = record.read_text(encoding="utf-8").splitlines()
    assert lines[0] == f"hook commit-msg {msgfile}"
    assert lines[1] == f"ORCH_HOME={ws.home}"


@needs_sh
def test_hook_script_warns_when_orch_missing(ws, tmp_path):
    fake_dir = tmp_path / "it's here too"
    fake_dir.mkdir()
    missing = fake_dir / "no-such-orch"

    script = fake_dir / "commit-msg"
    script.write_text(hook_script(ws, str(missing)))
    script.chmod(0o755)

    msgfile = tmp_path / "MSG"
    result = subprocess.run(["sh", str(script), str(msgfile)], capture_output=True, text=True,
                            env={"PATH": "/usr/bin:/bin"})
    assert result.returncode == 0
    assert "was NOT checked" in result.stderr


@needs_git
@pytest.mark.skipif(shutil.which("orch") is None, reason="orch executable not on PATH")
def test_hook_end_to_end(configure, ws_root, put):
    repo = ws_root / "hub"
    repo.mkdir()
    _git(repo, "init", "-q")
    ws = configure(git={"repos": {"hub": {}}})
    tid = put("in-progress", size="xs")
    install_hooks(ws)
    bad = _git(repo, "commit", "--allow-empty", "-q", "-m", "fix stuff")
    assert bad.returncode != 0 and "commit rejected" in bad.stderr
    good = _git(repo, "commit", "--allow-empty", "-q", "-m", f"{tid} Add thing", "-m", "What: a\nWhy: b\nRisk: c")
    assert good.returncode == 0, good.stderr


def test_cli_hook_commit_msg(ws_root, put, tmp_path, capsys):
    tid = put("in-progress", size="xs")
    msg = tmp_path / "COMMIT_EDITMSG"
    msg.write_text("nope\n", encoding="utf-8")
    assert run(["hook", "commit-msg", str(msg)]) == 1
    assert "commit rejected" in capsys.readouterr().err
    msg.write_text(f"{tid} Add thing{GOOD_BODY}", encoding="utf-8")
    assert run(["hook", "commit-msg", str(msg)]) == 0


@needs_git
def test_cli_hooks_install_json(configure, ws_root, capsys):
    repo = ws_root / "hub"
    repo.mkdir()
    _git(repo, "init", "-q")
    configure(git={"repos": {"hub": {}}})
    assert run(["hooks", "install", "--json"]) == 0
    rows = json.loads(capsys.readouterr().out)
    assert rows[0]["action"] == "installed" and rows[0]["repo"].endswith("hub")
