"""Which files the instructions become, per harness (harnesses §2).

* **Every harness:** ``AGENTS.orch.md`` in the workspace directory, and the built-in skills as ``SKILL.md`` folders.
* **Codex and other readers of ``AGENTS.md``:** one line in ``AGENTS.md`` that points to ``AGENTS.orch.md`` (created if
  there is no such file, appended otherwise; the line is never duplicated and nothing else in the file is touched).
* **Claude Code:** one ``@AGENTS.orch.md`` import line in ``CLAUDE.md`` handled the same way, and the plugin layout of
  ``plugins/orch-core/`` (``skills/`` and ``hooks/hooks.json``), generated by :func:`plugin_files` and kept equal to
  the repository by a test. The plugin's hooks run ``orch instructions hook session-start`` and ``pre-compact``.

The guard hook (tier C) is not part of this module.
"""

from __future__ import annotations

import json
import os
from collections.abc import Mapping
from pathlib import Path

from .agents_md import render_agents_md
from .skills import builtin_skills

__all__ = [
    "AGENTS_FILE",
    "AGENTS_POINTER",
    "CLAUDE_IMPORT",
    "SKILLS_DIR",
    "plugin_files",
    "workspace_files",
    "write_workspace_files",
]

AGENTS_FILE = "AGENTS.orch.md"
SKILLS_DIR = ".claude/skills"
AGENTS_POINTER = "Before working on tickets, read AGENTS.orch.md (orch)."
CLAUDE_IMPORT = "@AGENTS.orch.md"


def workspace_files(extra: tuple[str, ...] = ()) -> dict[str, str]:
    """``{path relative to the workspace: content}`` of the files orch owns and rewrites on ``instructions sync``."""
    files = {AGENTS_FILE: render_agents_md(extra)}
    for skill in builtin_skills():
        for rel, text in skill.files().items():
            files[f"{SKILLS_DIR}/{rel}"] = text
    return files


def plugin_files() -> dict[str, str]:
    """The plugin layout below ``plugins/orch-core/``: the skills and the hooks."""
    files = {f"skills/{rel}": text for skill in builtin_skills() for rel, text in skill.files().items()}
    hooks = {
        "hooks": {
            "SessionStart": [
                {
                    "matcher": "startup|resume|clear|compact",
                    "hooks": [{"type": "command", "command": "orch instructions hook session-start"}],
                }
            ],
            "PreCompact": [{"hooks": [{"type": "command", "command": "orch instructions hook pre-compact"}]}],
        }
    }
    files["hooks/hooks.json"] = json.dumps(hooks, indent=2) + "\n"
    return files


def _write(path: Path, text: str) -> bool:
    """Write ``text`` (LF, UTF-8) atomically unless it is already there; True if the file changed."""
    try:
        if path.read_text(encoding="utf-8") == text:
            return False
    except (FileNotFoundError, UnicodeDecodeError):
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp{os.getpid()}")
    tmp.write_bytes(text.encode("utf-8"))
    os.replace(tmp, path)
    return True


def _ensure_line(path: Path, line: str) -> bool:
    """Append ``line`` to ``path`` (created if missing) unless a line equal to it is there. True if the file changed."""
    try:
        have = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        have = ""
    if line in have.split("\n"):
        return False
    sep = "" if not have or have.endswith("\n") else "\n"
    return _write(path, have + sep + line + "\n")


def write_workspace_files(root: Path, *, pointers: bool = True, owned: Mapping[str, str] | None = None) -> list[str]:
    """Write the instruction files into ``root`` and return the relative paths that changed. ``pointers`` also adds the
    ``AGENTS.md`` and ``CLAUDE.md`` lines (``orch init`` does; ``instructions sync`` only rewrites what orch owns).

    A built-in skill whose sidecar says another scope than ``builtin`` was taken over by the owner and is left alone."""
    changed: list[str] = []
    for rel, text in (owned if owned is not None else workspace_files()).items():
        path = root / rel
        if rel.startswith(SKILLS_DIR + "/"):
            side = path.parent / "orch.skill.json"
            try:
                if json.loads(side.read_text(encoding="utf-8")).get("scope") not in (None, "builtin"):
                    continue
            except (OSError, ValueError, AttributeError):
                pass
        if _write(path, text):
            changed.append(rel)
    if pointers:
        for rel, line in (("AGENTS.md", AGENTS_POINTER), ("CLAUDE.md", CLAUDE_IMPORT)):
            if _ensure_line(root / rel, line):
                changed.append(rel)
    return changed
