from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from orch.core.fsutil import atomic_write_text
from orch.core.gitfiles import apply_ignore_block
from orch.instructions.blocks import apply_block, has_block
from orch.instructions.render import agents_block, claude_block, copilot_block, rules_file
from orch.instructions.settings import settings_text

SKILL_NAMES = ("orch-tickets", "orch-refine-ticket", "orch-work-on-ticket", "orch-setup")
_PACKAGED_SKILLS = Path(__file__).with_name("skills")  # present in built wheels (hatch force-include)
_SOURCE_SKILLS = Path(__file__).resolve().parents[3] / "skills"  # plugin root in a source checkout


def skills_dir() -> Path:
    return _PACKAGED_SKILLS if _PACKAGED_SKILLS.is_dir() else _SOURCE_SKILLS


GENERATED = "<!-- Generated by `orch instructions sync`; edits here are overwritten. -->"
AGENTS_STUB = ("## Customer notes\n\n<!-- Customer-specific facts, repo topology and extra rules. "
               "`orch instructions sync` never changes this part. -->")


@dataclass(frozen=True)
class SyncResult:
    path: Path
    action: str  # "created" | "updated" | "unchanged" | "needs-adopt"


def skill_text(name: str) -> str:
    raw = (skills_dir() / name / "SKILL.md").read_text(encoding="utf-8").replace("\r\n", "\n")
    end = raw.index("\n---\n", 4) + len("\n---\n")  # end of the YAML frontmatter
    text = raw[:end] + GENERATED + "\n" + raw[end:]
    return text if text.endswith("\n") else text + "\n"


Target = tuple[Path, Callable[[str | None], str], bool]  # (path, build(old) -> new, is a customer-shared file)


def _targets(ws) -> list[Target]:
    cfg, root = ws.config, ws.root
    harnesses = set(cfg.get("harnesses") or [])
    targets: list[Target] = [
        (ws.home / "AGENTS.orch.md", lambda old: rules_file(cfg), False),
        (ws.home / ".gitignore", apply_ignore_block, False),  # only the managed block; the rest is the human's
        (root / "AGENTS.md", lambda old: apply_block(old, agents_block(cfg), stub=AGENTS_STUB), True),
    ]
    skill_roots = []
    plugin = "claude-plugin" in harnesses
    if "claude" in harnesses or plugin:
        targets.append((root / "CLAUDE.md", lambda old: apply_block(old, claude_block(cfg)), True))
        targets.append((root / ".claude" / "settings.json",
                        lambda old: settings_text(old, cfg, plugin_mode=plugin, root=root), False))
        if not plugin:
            skill_roots.append(root / ".claude" / "skills")
    if "copilot" in harnesses:
        targets.append((root / ".github" / "copilot-instructions.md",
                        lambda old: apply_block(old, copilot_block(cfg)), True))
    if harnesses - {"claude", "claude-plugin"}:
        skill_roots.append(root / ".agents" / "skills")
    for base in skill_roots:
        for name in SKILL_NAMES:
            text = skill_text(name)
            targets.append((base / name / "SKILL.md", lambda old, text=text: text, False))
    return targets


def sync_instructions(ws, *, dry_run: bool = False, adopt: bool = False) -> list[SyncResult]:
    planned = []
    for path, build, shared in _targets(ws):  # compute everything first: any error aborts before writing
        old = path.read_bytes().decode("utf-8") if path.exists() else None  # keep CRLF: no newline translation
        if shared and old is not None and not has_block(old) and not adopt:
            planned.append((path, old, "needs-adopt"))  # a customer file orch has never managed: leave it alone
            continue
        new = build(old)
        if old is None:
            action = "created"
        elif old.replace("\r\n", "\n") == new.replace("\r\n", "\n"):
            action = "unchanged"
        else:
            action = "updated"
        planned.append((path, new, action))
    if not dry_run:
        for path, new, action in planned:
            if action in ("created", "updated"):
                atomic_write_text(path, new)
    return [SyncResult(path, action) for path, _, action in planned]
