from __future__ import annotations

import re
import shutil
import stat
import subprocess
from pathlib import Path

from orch.core.fsutil import atomic_write_text
from orch.errors import UsageError

HEADER = "# Generated by `orch hooks install`: checks commit messages against orchestrator/config.json."
HOOK = "commit-msg"
CHAINED = "commit-msg.pre-orch"


def _sq(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def _check_block(ws, orch_path: str) -> str:
    return (
        f"ORCH_HOME={_sq(str(ws.home))}; export ORCH_HOME\n"
        "if command -v orch >/dev/null 2>&1; then\n"
        "  orch hook commit-msg \"$1\" || exit $?\n"
        f"elif [ -x {_sq(orch_path)} ]; then\n"
        f"  {_sq(orch_path)} hook commit-msg \"$1\" || exit $?\n"
        "else\n"
        "  echo \"orch hook: the orch command was not found; this commit message was NOT checked "
        "(reinstall orch or run 'orch hooks install')\" >&2\n"
        "fi\n"
    )


def _stage_block(ws, orch_path: str) -> str:
    return (
        f"ORCH_HOME={_sq(str(ws.home))}; export ORCH_HOME\n"
        f"orch hook pre-commit >/dev/null 2>&1 || {_sq(orch_path)} hook pre-commit >/dev/null 2>&1 || true\n"
    )


def hook_script(ws, orch_path: str) -> str:
    return (
        "#!/bin/sh\n"
        f"{HEADER}\n"
        + _check_block(ws, orch_path)
        + "# a commit-msg hook that existed before orch was installed runs after the orch check\n"
        f"if [ -x \"$(dirname \"$0\")/{CHAINED}\" ]; then exec \"$(dirname \"$0\")/{CHAINED}\" \"$@\"; fi\n"
        "exit 0\n"
    )


PRE_COMMIT_HEADER = "# Generated by `orch hooks install --stage-records`: stages orch's own record with a ticket commit."


def pre_commit_script(ws, orch_path: str) -> str:
    return f"#!/bin/sh\n{PRE_COMMIT_HEADER}\n" + _stage_block(ws, orch_path) + "exit 0\n"


def _write_pre_commit(hooks_dir: Path, script: str) -> str:
    target = hooks_dir / "pre-commit"
    try:
        if target.exists() and target.read_text(encoding="utf-8", errors="replace").split("\n", 2)[1:2] != [PRE_COMMIT_HEADER]:
            return "skipped: a pre-commit hook already exists"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        atomic_write_text(target, script)
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError as e:
        return f"failed: {target}: {e}"
    return "installed"


def is_orch_hook(text: str) -> bool:
    return text.split("\n", 2)[1:2] == [HEADER]


# A repo whose core.hooksPath points at a folder of its own (usually tracked in the repo) never runs .git/hooks. Its
# commit-msg there gets this block: it runs the clone's own generated hook (machine-specific paths, so never
# tracked) when there is one, and does nothing in a clone without orch.
DELEGATE_BEGIN = "# >>> orch commit-msg check >>>"
DELEGATE_END = "# <<< orch commit-msg check <<<"
PRE_DELEGATE_BEGIN = "# >>> orch pre-commit stage >>>"
PRE_DELEGATE_END = "# <<< orch pre-commit stage <<<"


def _delegate(hook: str, begin: str, end: str, what: str) -> str:
    return (
        f"{begin}\n"
        f"# Runs this clone's orch {what} if `orch hooks install` set one up; a clone without one skips it.\n"
        f'orch_hook="$(git rev-parse --git-common-dir)/hooks/{hook}"\n'
        'if [ -x "$orch_hook" ]; then "$orch_hook" "$@" || exit $?; fi\n'
        f"{end}\n"
    )


DELEGATE = _delegate(HOOK, DELEGATE_BEGIN, DELEGATE_END, "commit-message check")
PRE_DELEGATE = _delegate("pre-commit", PRE_DELEGATE_BEGIN, PRE_DELEGATE_END, "record staging")
_SHELL = re.compile(r"^#!\s*(?:/usr/bin/env\s+)?(?:\S*/)?(?:sh|bash|dash|zsh|ksh)(?:\s|$)")


def has_delegate(text: str) -> bool:
    return DELEGATE_BEGIN in text


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, encoding="utf-8", check=False)


def _git_error(what: str, r: subprocess.CompletedProcess) -> str:
    detail = (r.stderr or r.stdout).strip() or f"exit code {r.returncode}"
    return f"failed: git {what}: {detail}"


def configured_repos(ws) -> list[Path]:
    repos = ws.config["git"].get("repos") or {}
    return [(ws.root / ((r or {}).get("path") or name)).resolve() for name, r in repos.items()]


def check_off_repos(ws) -> set[Path]:
    """Repos whose `git.repos.<name>.commit_check` is `off` (#170): no hook goes there, on purpose."""
    from orch.hooks.commit_msg import commit_check_mode
    repos = ws.config["git"].get("repos") or {}
    return {(ws.root / ((r or {}).get("path") or name)).resolve()
            for name, r in repos.items() if commit_check_mode(ws.config, name) == "off"}


def _config_value(repo: Path, *scope: str) -> tuple[str | None, str | None]:
    """(value, error) of core.hooksPath; git exits 1 when the key is simply not set."""
    r = _git(repo, "config", *scope, "--get", "core.hooksPath")
    if r.returncode == 0:
        return r.stdout.strip(), None
    if r.returncode == 1:
        return None, None
    return None, _git_error("config --get core.hooksPath", r)


def _hooks_dir(repo: Path, *rev_parse: str) -> tuple[Path | None, str | None]:
    r = _git(repo, "rev-parse", *rev_parse)
    if r.returncode != 0 or not r.stdout.strip():
        return None, _git_error("rev-parse " + " ".join(rev_parse), r)
    found = Path(r.stdout.strip()).expanduser()
    return (found if found.is_absolute() else repo / found).resolve(), None


def _common_hooks_dir(repo: Path) -> tuple[Path | None, str | None]:
    """<git common dir>/hooks: where git looks without core.hooksPath, shared by all worktrees, never tracked."""
    common, err = _hooks_dir(repo, "--git-common-dir")
    return (common / "hooks" if common else None), err


def _install_one(repo: Path, script: str, force: bool, pre_commit: str | None = None) -> str:
    if not repo.is_dir() or _git(repo, "rev-parse", "--git-dir").returncode != 0:
        return "skipped: not a git repository"
    local, err = _config_value(repo, "--local")
    if err:
        return err
    effective, err = _config_value(repo)
    if err:
        return err
    # --git-path hooks honours core.hooksPath and is shared by all worktrees of the repo
    hooks_dir, err = _hooks_dir(repo, "--git-path", "hooks")
    if err:
        return err
    if local or effective:
        common, err = _common_hooks_dir(repo)
        if err:
            return err
        if common != hooks_dir:
            target, skip = _delegate_target(repo, hooks_dir, local, local or effective)
            got = skip if target is None else _install_with_hooks_path(repo, target, common, script, force, pre_commit)
            if pre_commit and "; pre-commit " not in got:  # never silent: say the record hook was not installed
                got += "; pre-commit not installed: add `orch hook pre-commit` to the hook that runs there by hand"
            return got
    action = _write_hook(hooks_dir, script, force)
    if pre_commit and action.startswith(("installed", "updated", "unchanged")):
        action += f"; pre-commit {_write_pre_commit(hooks_dir, pre_commit)}"
    return action


def _ignored(repo: Path, path: Path) -> bool:
    return _git(repo, "check-ignore", "-q", "--", str(path)).returncode == 0


def _delegate_target(repo: Path, hooks_dir: Path, local: str | None, value: str) -> tuple[Path | None, str | None]:
    """(the tracked commit-msg that gets DELEGATE, None) for a core.hooksPath this repo owns, else (None, why not).

    Only a core.hooksPath from the repo's own (--local) config that lies inside its worktree is the repo's: one from
    the global or system config serves every repo of the user, and a folder outside the worktree is not part of the
    repository either; neither is ever written. A git-ignored folder is generated by some tool (husky v9 sets
    .husky/_ and rewrites it on install): for husky the call goes into the tracked .husky/commit-msg that its
    generated hook runs; for anything else it is left to the user."""
    by_hand = f"skipped: core.hooksPath is set to {value}; add `orch hook commit-msg \"$1\"` to that hook manually"
    if not local:
        return None, by_hand
    top, err = _hooks_dir(repo, "--show-toplevel")
    if err or not hooks_dir.is_relative_to(top):
        return None, by_hand
    if not _ignored(repo, hooks_dir / HOOK):
        return hooks_dir / HOOK, None
    if hooks_dir.name == "_" and hooks_dir.parent.name == ".husky" and not _ignored(repo, hooks_dir.parent / HOOK):
        return hooks_dir.parent / HOOK, None
    return None, (f"skipped: core.hooksPath {value} is ignored by git (generated by some tool), so orch does not "
                  "write there; add `orch hook commit-msg \"$1\"` to the tracked hook that tool runs, by hand")


def _is_husky_hook(path: Path) -> bool:
    """.husky/<hook>: husky v9 runs these with sh, so they need no shebang."""
    return path.parent.name == ".husky"


def _write_hook(hooks_dir: Path, script: str, force: bool) -> str:
    """The generated hook as <hooks_dir>/commit-msg; an existing foreign one is kept as commit-msg.pre-orch (--force)."""
    target, chained = hooks_dir / HOOK, hooks_dir / CHAINED
    note = ""
    try:
        if target.exists() or target.is_symlink():
            current = target.read_text(encoding="utf-8", errors="replace") if target.is_file() else ""
            if is_orch_hook(current):
                if current == script:
                    return "unchanged"
                action = "updated"
            elif not force:
                return (f"skipped: a commit-msg hook already exists in {hooks_dir} "
                        f"(use --force to keep it as {CHAINED}, run after the orch check)")
            elif chained.exists() or chained.is_symlink():
                return (f"skipped: {hooks_dir} has both commit-msg and {CHAINED}; "
                        "merge them by hand, then re-run `orch hooks install`")
            else:
                target.rename(chained)
                action, note = "installed", f" (the existing commit-msg now runs as {CHAINED})"
        else:
            action = "installed"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        atomic_write_text(target, script)
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError as e:
        if note and not target.exists() and chained.exists():
            chained.rename(target)  # put the customer's hook back where it was
        return f"failed: {target}: {e}"
    return action + note


def _install_with_hooks_path(repo: Path, tracked: Path, common: Path, script: str, force: bool,
                             pre_commit: str | None = None) -> str:
    """core.hooksPath points at a folder of the repo's own: the generated hook goes to <common dir>/hooks as usual
    (git does not run it from there by itself) and the core.hooksPath folder's commit-msg gets DELEGATE, which runs
    it. That commit-msg is part of the repository, so the result always says it has to be committed;
    core.hooksPath itself is never changed."""
    tracked_dir = tracked.parent
    try:
        shown = tracked.relative_to(repo.resolve()).as_posix()
    except ValueError:
        shown = str(tracked)
    commit_note = f"{shown} belongs to the repository: commit it so the check stays in place"
    current = None
    if tracked.is_symlink():
        return f"skipped: {tracked} is a symbolic link; add `orch hook commit-msg \"$1\"` to its target by hand"
    if tracked.exists():
        try:
            current = tracked.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as e:
            return f"skipped: cannot read {tracked} ({e}); add `orch hook commit-msg \"$1\"` to it by hand"
        if (not is_orch_hook(current) and not has_delegate(current) and not _SHELL.match(current)
                and not (_is_husky_hook(tracked) and not current.startswith("#!"))):
            return (f"skipped: {tracked} is not a shell script; add a call to `orch hook commit-msg \"$1\"` "
                    "to it by hand, then commit it")
    action = _write_hook(common, script, force)
    if not action.startswith(("installed", "updated", "unchanged")):
        return action
    extra = f"; pre-commit {_delegate_pre_commit(repo, tracked.parent / 'pre-commit', common, pre_commit)}" if pre_commit else ""
    if current is not None and (is_orch_hook(current) or has_delegate(current)):
        return f"{action}; {shown} already runs it ({commit_note}){extra}"
    try:
        if current is None:
            tracked_dir.mkdir(parents=True, exist_ok=True)
            atomic_write_text(tracked, DELEGATE if _is_husky_hook(tracked) else "#!/bin/sh\n" + DELEGATE)
            tracked.chmod(0o755)  # git records it as an executable file
            what = f"created {shown}, which runs it"
        else:
            nl = "\r\n" if "\r\n" in current else "\n"
            block = DELEGATE.replace("\n", nl)
            if current.startswith("#!"):
                shebang, sep, rest = current.partition("\n")
                head, rest = shebang + sep, rest
            else:  # a husky hook: no shebang, the block goes first
                head, rest = "", current
            mode = stat.S_IMODE(tracked.stat().st_mode)
            atomic_write_text(tracked, head + block + rest)  # right after the shebang: before any exit
            tracked.chmod(mode)  # the rewrite is a new file: keep the old one's permissions
            what = f"added the call to {shown}"
            if not mode & stat.S_IXUSR and not _is_husky_hook(tracked):
                what += " (it is not executable, so git does not run it yet: chmod +x it)"
    except OSError as e:
        return f"{action}; failed: {tracked}: {e}"
    return f"{action if action != 'unchanged' else 'installed'}; {what} ({commit_note}){extra}"


def _delegate_pre_commit(repo: Path, tracked: Path, common: Path, script: str) -> str:
    """The record staging hook under a repo-owned core.hooksPath: the generated one goes to <common dir>/hooks and
    the tracked pre-commit there gets PRE_DELEGATE, the way commit-msg does. A foreign hook is only extended, never
    replaced; one that is not a shell script is left to the user."""
    try:
        shown = tracked.relative_to(repo.resolve()).as_posix()
    except ValueError:
        shown = str(tracked)
    if tracked.is_symlink():
        return f"skipped: {tracked} is a symbolic link; add `orch hook pre-commit` to its target by hand"
    current = None
    try:
        if tracked.exists():
            current = tracked.read_text(encoding="utf-8")
            if (PRE_DELEGATE_BEGIN not in current and not _SHELL.match(current)
                    and not (_is_husky_hook(tracked) and not current.startswith("#!"))):
                return f"skipped: {tracked} is not a shell script; add a call to `orch hook pre-commit` to it by hand"
        done = _write_pre_commit(common, script)
        if done != "installed":
            return done
        if current is not None and PRE_DELEGATE_BEGIN in current:
            return f"installed; {shown} already runs it (commit it so the staging stays in place)"
        if current is None:
            tracked.parent.mkdir(parents=True, exist_ok=True)
            atomic_write_text(tracked, PRE_DELEGATE if _is_husky_hook(tracked) else "#!/bin/sh\n" + PRE_DELEGATE)
            tracked.chmod(0o755)
            what = f"created {shown}"
        else:
            nl = "\r\n" if "\r\n" in current else "\n"
            block = PRE_DELEGATE.replace("\n", nl)
            head, rest = (current.partition("\n")[0] + "\n", current.partition("\n")[2]) if current.startswith("#!") else ("", current)
            mode = stat.S_IMODE(tracked.stat().st_mode)
            atomic_write_text(tracked, head + block + rest)
            tracked.chmod(mode)
            what = f"added the call to {shown}"
    except (OSError, UnicodeDecodeError) as e:
        return f"failed: {tracked}: {e}"
    return f"installed; {what} (commit it so the staging stays in place)"


# --untracked: this clone's own core.hooksPath points at <git common dir>/orch-hooks, which git never tracks. Each
# hook there runs orch's part, then execs the hook that ran before, so no tracked file and no existing hook changes.
UNTRACKED_DIR = "orch-hooks"
UNTRACKED_HEADER = "# Generated by `orch hooks install --untracked`: runs orch's part, then the hook that ran before."
BEFORE_KEY = "orch.hooksPathBefore"  # the effective core.hooksPath before the install ("" = git's default)
LOCAL_BEFORE_KEY = "orch.localHooksPathBefore"  # the clone's own value, put back by `orch hooks uninstall`
# Client-side hooks a clone may run: each gets a wrapper, so moving core.hooksPath switches none of them off.
CLIENT_HOOKS = ("applypatch-msg", "pre-applypatch", "post-applypatch", "pre-commit", "pre-merge-commit",
                "prepare-commit-msg", "commit-msg", "post-commit", "pre-rebase", "post-checkout", "post-merge",
                "pre-push", "post-rewrite", "pre-auto-gc", "post-index-change", "sendemail-validate")


def untracked_script(name: str, before: str, orch_part: str = "") -> str:
    # a relative hooksPath is relative to where git runs hooks, which is the cwd here too
    return (
        "#!/bin/sh\n"
        f"{UNTRACKED_HEADER}\n"
        + orch_part
        + f"orig={_sq(before)}\n"
        '[ -n "$orig" ] || orig="$(git rev-parse --git-common-dir)/hooks"\n'
        f'if [ -x "$orig/{name}" ]; then exec "$orig/{name}" "$@"; fi\n'
        "exit 0\n"
    )


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _is_untracked_hook(path: Path) -> bool:
    return _read(path).split("\n", 2)[1:2] == [UNTRACKED_HEADER]


def _untracked_dir(repo: Path) -> tuple[Path | None, str | None]:
    common, err = _hooks_dir(repo, "--git-common-dir")
    return (common / UNTRACKED_DIR if common else None), err


def _points_at(value: str | None, folder: Path | None) -> bool:
    if not value or folder is None:
        return False
    path = Path(value).expanduser()
    return path.is_absolute() and path.resolve() == folder


def untracked_active(repo: Path) -> bool:
    """This clone's core.hooksPath is orch's untracked hooks folder."""
    if not repo.is_dir() or _git(repo, "rev-parse", "--git-dir").returncode != 0:
        return False
    folder, err = _untracked_dir(repo)
    local, _ = _config_value(repo, "--local")
    return err is None and _points_at(local, folder)


def _get(repo: Path, key: str) -> str | None:
    r = _git(repo, "config", "--local", "--get", key)
    return r.stdout.rstrip("\n") if r.returncode == 0 else None


def _previous_dir(repo: Path, before: str, common_hooks: Path) -> Path:
    if not before:
        return common_hooks
    path = Path(before).expanduser()
    if path.is_absolute():
        return path
    top, err = _hooks_dir(repo, "--show-toplevel")
    return (top if top is not None and not err else repo) / path


def _install_untracked(repo: Path, ws, orch_path: str, stage: bool) -> str:
    if not repo.is_dir() or _git(repo, "rev-parse", "--git-dir").returncode != 0:
        return "skipped: not a git repository"
    folder, err = _untracked_dir(repo)
    if err:
        return err
    common_hooks, err = _common_hooks_dir(repo)
    if err:
        return err
    local, err = _config_value(repo, "--local")
    if err:
        return err
    active = _points_at(local, folder)
    if active:
        before = _get(repo, BEFORE_KEY) or ""
        stage = stage or "hook pre-commit" in _read(folder / "pre-commit")  # a re-run keeps the record staging
    else:
        r = _git(repo, "config", "--path", "--get", "core.hooksPath")
        if r.returncode not in (0, 1):
            return _git_error("config --get core.hooksPath", r)
        before = r.stdout.strip() if r.returncode == 0 else ""
    previous = _previous_dir(repo, before, common_hooks)
    names = list(CLIENT_HOOKS)
    try:  # hooks of other names in the previous folder (git-p4, reference-transaction, ...) keep running too
        names += sorted(p.name for p in previous.iterdir() if p.is_file() and "." not in p.name
                        and p.name not in CLIENT_HOOKS and p.stat().st_mode & stat.S_IXUSR)
    except OSError:
        pass
    parts = {HOOK: _check_block(ws, orch_path)}
    if stage:
        parts["pre-commit"] = _stage_block(ws, orch_path)
    changed = False
    try:
        folder.mkdir(exist_ok=True)
        for name in names:
            target, text = folder / name, untracked_script(name, before, parts.get(name, ""))
            if target.exists() and not _is_untracked_hook(target):
                return f"skipped: {target} was not written by orch; move it away, then re-run"
            if _read(target) == text:
                continue
            atomic_write_text(target, text)
            target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            changed = True
    except OSError as e:
        return f"failed: {folder}: {e}"
    if active:
        return "updated" if changed else "unchanged"
    sets = [(LOCAL_BEFORE_KEY, local)] if local is not None else []
    sets += [(BEFORE_KEY, before), ("core.hooksPath", str(folder))]
    for key, value in sets:  # core.hooksPath last: git switches over only once every wrapper is in place
        r = _git(repo, "config", "--local", key, value)
        if r.returncode != 0:
            return _git_error(f"config {key}", r)
    note = (f"; note: the previous core.hooksPath {before} does not exist, so the repo's own hooks did not run "
            "before either") if before and not previous.is_dir() else ""
    return (f"installed (untracked: core.hooksPath now points at {folder}; each hook there runs orch's part, then "
            f"the hook from {before or '.git/hooks'}; no tracked file changed){note}")


def uninstall_untracked(repo: Path) -> str:
    """Undo `--untracked`: the clone's previous core.hooksPath comes back and orch's wrapper folder goes."""
    if not untracked_active(repo):
        return "skipped: not installed with --untracked"
    folder, _ = _untracked_dir(repo)
    local = _get(repo, LOCAL_BEFORE_KEY)
    r = (_git(repo, "config", "--local", "core.hooksPath", local) if local is not None
         else _git(repo, "config", "--local", "--unset", "core.hooksPath"))
    if r.returncode != 0:
        return _git_error("config core.hooksPath", r)
    for key in (LOCAL_BEFORE_KEY, BEFORE_KEY):
        _git(repo, "config", "--local", "--unset", key)
    try:
        for p in folder.iterdir():
            if _is_untracked_hook(p):
                p.unlink()
        folder.rmdir()
    except OSError:
        pass  # a file orch did not write stays, and so does the folder
    return f"removed (core.hooksPath is {local} again)" if local is not None else "removed (core.hooksPath unset again)"


def missing_hooks_path(repo: Path) -> Path | None:
    """The folder a set core.hooksPath points to when it does not exist: git then runs none of the repo's hooks."""
    if not repo.is_dir():
        return None
    value, err = _config_value(repo)
    if not value or err:
        return None
    hooks_dir, err = _hooks_dir(repo, "--git-path", "hooks")
    return hooks_dir if hooks_dir is not None and not err and not hooks_dir.is_dir() else None


def hook_state(repo: Path) -> str:
    """Read-only: installed | missing | foreign | hooks-path | not-a-repo."""
    if not repo.is_dir() or _git(repo, "rev-parse", "--git-dir").returncode != 0:
        return "not-a-repo"
    hooks_dir, _ = _hooks_dir(repo, "--git-path", "hooks")
    local, _ = _config_value(repo, "--local")
    effective, _ = _config_value(repo)
    folder, _ = _untracked_dir(repo)
    if _points_at(local, folder):
        return "installed" if "hook commit-msg" in _read(folder / HOOK) else "missing"
    if hooks_dir is not None:
        target = hooks_dir / HOOK
        common, _ = _common_hooks_dir(repo)
        if (local or effective) and common != hooks_dir:
            found, _ = _delegate_target(repo, hooks_dir, local, local or effective)
            target = found or target
        if target.is_file():
            text = target.read_text(encoding="utf-8", errors="replace")
            if is_orch_hook(text):
                return "installed"
            if has_delegate(text):  # core.hooksPath: covered once this clone has its own generated hook too
                own = common / HOOK if common is not None else None
                ok = own is not None and own.is_file() and is_orch_hook(own.read_text(encoding="utf-8", errors="replace"))
                return "installed" if ok else "missing"
            return "foreign"
    return "hooks-path" if (local or effective) else "missing"


def records_unversioned(ws) -> bool:
    """The workspace is in no git repository, so orch's records have no history to stage into."""
    return _git(ws.root, "rev-parse", "--show-toplevel").returncode != 0


def install_hooks(ws, repos: list[Path] | None = None, *, force: bool = False, stage_records: bool = False,
                  untracked: bool = False) -> list[tuple[Path, str]]:
    targets = [Path(p).resolve() for p in repos] if repos else configured_repos(ws)
    if not targets:
        raise UsageError("no repositories to install into",
                         hint="add git.repos to orchestrator/config.json or pass --repo PATH")
    orch_path = shutil.which("orch") or "orch"
    skip_note = ""
    if stage_records and records_unversioned(ws):
        stage_records = False
        skip_note = (f"; pre-commit skipped: the workspace root {ws.root} is not a git repository, so orch's records "
                     "are local only and there is nothing to stage (`orch doctor --init-git` makes it a local-only "
                     "repository)")
    pre_commit = pre_commit_script(ws, orch_path) if stage_records else None
    rows = []
    off = check_off_repos(ws)
    for repo in targets:
        if repo in off:
            rows.append((repo, "skipped: commit_check is off for this repo (git.repos.<name>.commit_check)"))
            continue
        if untracked or untracked_active(repo):
            action = _install_untracked(repo, ws, orch_path, stage_records)
        else:
            action = _install_one(repo, hook_script(ws, orch_path), force, pre_commit)
        rows.append((repo, action + skip_note))
    return rows
