from __future__ import annotations

import re
import shutil
import stat
import subprocess
from pathlib import Path

from orch.core.fsutil import atomic_write_text
from orch.errors import UsageError

HEADER = "# Generated by `orch hooks install`: checks commit messages against orchestrator/config.json."
HOOK = "commit-msg"
CHAINED = "commit-msg.pre-orch"


def _sq(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def hook_script(ws, orch_path: str) -> str:
    return (
        "#!/bin/sh\n"
        f"{HEADER}\n"
        f"ORCH_HOME={_sq(str(ws.home))}; export ORCH_HOME\n"
        "if command -v orch >/dev/null 2>&1; then\n"
        "  orch hook commit-msg \"$1\" || exit $?\n"
        f"elif [ -x {_sq(orch_path)} ]; then\n"
        f"  {_sq(orch_path)} hook commit-msg \"$1\" || exit $?\n"
        "else\n"
        "  echo \"orch hook: the orch command was not found; this commit message was NOT checked "
        "(reinstall orch or run 'orch hooks install')\" >&2\n"
        "fi\n"
        "# a commit-msg hook that existed before orch was installed runs after the orch check\n"
        f"if [ -x \"$(dirname \"$0\")/{CHAINED}\" ]; then exec \"$(dirname \"$0\")/{CHAINED}\" \"$@\"; fi\n"
        "exit 0\n"
    )


PRE_COMMIT_HEADER = "# Generated by `orch hooks install --stage-records`: stages orch's own record with a ticket commit."


def pre_commit_script(ws, orch_path: str) -> str:
    return (
        "#!/bin/sh\n"
        f"{PRE_COMMIT_HEADER}\n"
        f"ORCH_HOME={_sq(str(ws.home))}; export ORCH_HOME\n"
        f"orch hook pre-commit >/dev/null 2>&1 || {_sq(orch_path)} hook pre-commit >/dev/null 2>&1 || true\n"
        "exit 0\n"
    )


def _write_pre_commit(hooks_dir: Path, script: str) -> str:
    target = hooks_dir / "pre-commit"
    try:
        if target.exists() and target.read_text(encoding="utf-8", errors="replace").split("\n", 2)[1:2] != [PRE_COMMIT_HEADER]:
            return "skipped: a pre-commit hook already exists"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        atomic_write_text(target, script)
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError as e:
        return f"failed: {target}: {e}"
    return "installed"


def is_orch_hook(text: str) -> bool:
    return text.split("\n", 2)[1:2] == [HEADER]


# A repo whose core.hooksPath points at a folder of its own (usually tracked in the repo) never runs .git/hooks. Its
# commit-msg there gets this block: it runs the clone's own generated hook (machine-specific paths, so never
# tracked) when there is one, and does nothing in a clone without orch.
DELEGATE_BEGIN = "# >>> orch commit-msg check >>>"
DELEGATE_END = "# <<< orch commit-msg check <<<"
DELEGATE = (
    f"{DELEGATE_BEGIN}\n"
    "# Runs this clone's orch commit-message check if `orch hooks install` set one up; a clone without one skips it.\n"
    'orch_hook="$(git rev-parse --git-common-dir)/hooks/commit-msg"\n'
    'if [ -x "$orch_hook" ]; then "$orch_hook" "$@" || exit $?; fi\n'
    f"{DELEGATE_END}\n"
)
_SHELL = re.compile(r"^#!\s*(?:/usr/bin/env\s+)?(?:\S*/)?(?:sh|bash|dash|zsh|ksh)(?:\s|$)")


def has_delegate(text: str) -> bool:
    return DELEGATE_BEGIN in text


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, encoding="utf-8", check=False)


def _git_error(what: str, r: subprocess.CompletedProcess) -> str:
    detail = (r.stderr or r.stdout).strip() or f"exit code {r.returncode}"
    return f"failed: git {what}: {detail}"


def configured_repos(ws) -> list[Path]:
    repos = ws.config["git"].get("repos") or {}
    return [(ws.root / ((r or {}).get("path") or name)).resolve() for name, r in repos.items()]


def _config_value(repo: Path, *scope: str) -> tuple[str | None, str | None]:
    """(value, error) of core.hooksPath; git exits 1 when the key is simply not set."""
    r = _git(repo, "config", *scope, "--get", "core.hooksPath")
    if r.returncode == 0:
        return r.stdout.strip(), None
    if r.returncode == 1:
        return None, None
    return None, _git_error("config --get core.hooksPath", r)


def _hooks_dir(repo: Path, *rev_parse: str) -> tuple[Path | None, str | None]:
    r = _git(repo, "rev-parse", *rev_parse)
    if r.returncode != 0 or not r.stdout.strip():
        return None, _git_error("rev-parse " + " ".join(rev_parse), r)
    found = Path(r.stdout.strip()).expanduser()
    return (found if found.is_absolute() else repo / found).resolve(), None


def _common_hooks_dir(repo: Path) -> tuple[Path | None, str | None]:
    """<git common dir>/hooks: where git looks without core.hooksPath, shared by all worktrees, never tracked."""
    common, err = _hooks_dir(repo, "--git-common-dir")
    return (common / "hooks" if common else None), err


def _install_one(repo: Path, script: str, force: bool, pre_commit: str | None = None) -> str:
    if not repo.is_dir() or _git(repo, "rev-parse", "--git-dir").returncode != 0:
        return "skipped: not a git repository"
    local, err = _config_value(repo, "--local")
    if err:
        return err
    effective, err = _config_value(repo)
    if err:
        return err
    # --git-path hooks honours core.hooksPath and is shared by all worktrees of the repo
    hooks_dir, err = _hooks_dir(repo, "--git-path", "hooks")
    if err:
        return err
    if local or effective:
        common, err = _common_hooks_dir(repo)
        if err:
            return err
        if common != hooks_dir:
            target, skip = _delegate_target(repo, hooks_dir, local, local or effective)
            if target is None:
                return skip
            return _install_with_hooks_path(repo, target, common, script, force)
    action = _write_hook(hooks_dir, script, force)
    if pre_commit and action.startswith(("installed", "updated", "unchanged")):
        action += f"; pre-commit {_write_pre_commit(hooks_dir, pre_commit)}"
    return action


def _ignored(repo: Path, path: Path) -> bool:
    return _git(repo, "check-ignore", "-q", "--", str(path)).returncode == 0


def _delegate_target(repo: Path, hooks_dir: Path, local: str | None, value: str) -> tuple[Path | None, str | None]:
    """(the tracked commit-msg that gets DELEGATE, None) for a core.hooksPath this repo owns, else (None, why not).

    Only a core.hooksPath from the repo's own (--local) config that lies inside its worktree is the repo's: one from
    the global or system config serves every repo of the user, and a folder outside the worktree is not part of the
    repository either; neither is ever written. A git-ignored folder is generated by some tool (husky v9 sets
    .husky/_ and rewrites it on install): for husky the call goes into the tracked .husky/commit-msg that its
    generated hook runs; for anything else it is left to the user."""
    by_hand = f"skipped: core.hooksPath is set to {value}; add `orch hook commit-msg \"$1\"` to that hook manually"
    if not local:
        return None, by_hand
    top, err = _hooks_dir(repo, "--show-toplevel")
    if err or not hooks_dir.is_relative_to(top):
        return None, by_hand
    if not _ignored(repo, hooks_dir / HOOK):
        return hooks_dir / HOOK, None
    if hooks_dir.name == "_" and hooks_dir.parent.name == ".husky" and not _ignored(repo, hooks_dir.parent / HOOK):
        return hooks_dir.parent / HOOK, None
    return None, (f"skipped: core.hooksPath {value} is ignored by git (generated by some tool), so orch does not "
                  "write there; add `orch hook commit-msg \"$1\"` to the tracked hook that tool runs, by hand")


def _is_husky_hook(path: Path) -> bool:
    """.husky/<hook>: husky v9 runs these with sh, so they need no shebang."""
    return path.parent.name == ".husky"


def _write_hook(hooks_dir: Path, script: str, force: bool) -> str:
    """The generated hook as <hooks_dir>/commit-msg; an existing foreign one is kept as commit-msg.pre-orch (--force)."""
    target, chained = hooks_dir / HOOK, hooks_dir / CHAINED
    note = ""
    try:
        if target.exists() or target.is_symlink():
            current = target.read_text(encoding="utf-8", errors="replace") if target.is_file() else ""
            if is_orch_hook(current):
                if current == script:
                    return "unchanged"
                action = "updated"
            elif not force:
                return (f"skipped: a commit-msg hook already exists in {hooks_dir} "
                        f"(use --force to keep it as {CHAINED}, run after the orch check)")
            elif chained.exists() or chained.is_symlink():
                return (f"skipped: {hooks_dir} has both commit-msg and {CHAINED}; "
                        "merge them by hand, then re-run `orch hooks install`")
            else:
                target.rename(chained)
                action, note = "installed", f" (the existing commit-msg now runs as {CHAINED})"
        else:
            action = "installed"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        atomic_write_text(target, script)
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError as e:
        if note and not target.exists() and chained.exists():
            chained.rename(target)  # put the customer's hook back where it was
        return f"failed: {target}: {e}"
    return action + note


def _install_with_hooks_path(repo: Path, tracked: Path, common: Path, script: str, force: bool) -> str:
    """core.hooksPath points at a folder of the repo's own: the generated hook goes to <common dir>/hooks as usual
    (git does not run it from there by itself) and the core.hooksPath folder's commit-msg gets DELEGATE, which runs
    it. That commit-msg is part of the repository, so the result always says it has to be committed;
    core.hooksPath itself is never changed."""
    tracked_dir = tracked.parent
    try:
        shown = tracked.relative_to(repo.resolve()).as_posix()
    except ValueError:
        shown = str(tracked)
    commit_note = f"{shown} belongs to the repository: commit it so the check stays in place"
    current = None
    if tracked.is_symlink():
        return f"skipped: {tracked} is a symbolic link; add `orch hook commit-msg \"$1\"` to its target by hand"
    if tracked.exists():
        try:
            current = tracked.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as e:
            return f"skipped: cannot read {tracked} ({e}); add `orch hook commit-msg \"$1\"` to it by hand"
        if (not is_orch_hook(current) and not has_delegate(current) and not _SHELL.match(current)
                and not (_is_husky_hook(tracked) and not current.startswith("#!"))):
            return (f"skipped: {tracked} is not a shell script; add a call to `orch hook commit-msg \"$1\"` "
                    "to it by hand, then commit it")
    action = _write_hook(common, script, force)
    if not action.startswith(("installed", "updated", "unchanged")):
        return action
    if current is not None and (is_orch_hook(current) or has_delegate(current)):
        return f"{action}; {shown} already runs it ({commit_note})"
    try:
        if current is None:
            tracked_dir.mkdir(parents=True, exist_ok=True)
            atomic_write_text(tracked, DELEGATE if _is_husky_hook(tracked) else "#!/bin/sh\n" + DELEGATE)
            tracked.chmod(0o755)  # git records it as an executable file
            what = f"created {shown}, which runs it"
        else:
            nl = "\r\n" if "\r\n" in current else "\n"
            block = DELEGATE.replace("\n", nl)
            if current.startswith("#!"):
                shebang, sep, rest = current.partition("\n")
                head, rest = shebang + sep, rest
            else:  # a husky hook: no shebang, the block goes first
                head, rest = "", current
            mode = stat.S_IMODE(tracked.stat().st_mode)
            atomic_write_text(tracked, head + block + rest)  # right after the shebang: before any exit
            tracked.chmod(mode)  # the rewrite is a new file: keep the old one's permissions
            what = f"added the call to {shown}"
            if not mode & stat.S_IXUSR and not _is_husky_hook(tracked):
                what += " (it is not executable, so git does not run it yet: chmod +x it)"
    except OSError as e:
        return f"{action}; failed: {tracked}: {e}"
    return f"{action if action != 'unchanged' else 'installed'}; {what} ({commit_note})"


def hook_state(repo: Path) -> str:
    """Read-only: installed | missing | foreign | hooks-path | not-a-repo."""
    if not repo.is_dir() or _git(repo, "rev-parse", "--git-dir").returncode != 0:
        return "not-a-repo"
    hooks_dir, _ = _hooks_dir(repo, "--git-path", "hooks")
    local, _ = _config_value(repo, "--local")
    effective, _ = _config_value(repo)
    if hooks_dir is not None:
        target = hooks_dir / HOOK
        common, _ = _common_hooks_dir(repo)
        if (local or effective) and common != hooks_dir:
            found, _ = _delegate_target(repo, hooks_dir, local, local or effective)
            target = found or target
        if target.is_file():
            text = target.read_text(encoding="utf-8", errors="replace")
            if is_orch_hook(text):
                return "installed"
            if has_delegate(text):  # core.hooksPath: covered once this clone has its own generated hook too
                own = common / HOOK if common is not None else None
                ok = own is not None and own.is_file() and is_orch_hook(own.read_text(encoding="utf-8", errors="replace"))
                return "installed" if ok else "missing"
            return "foreign"
    return "hooks-path" if (local or effective) else "missing"


def install_hooks(ws, repos: list[Path] | None = None, *, force: bool = False, stage_records: bool = False) -> list[tuple[Path, str]]:
    targets = [Path(p).resolve() for p in repos] if repos else configured_repos(ws)
    if not targets:
        raise UsageError("no repositories to install into",
                         hint="add git.repos to orchestrator/config.json or pass --repo PATH")
    orch_path = shutil.which("orch") or "orch"
    pre_commit = pre_commit_script(ws, orch_path) if stage_records else None
    return [(repo, _install_one(repo, hook_script(ws, orch_path), force, pre_commit)) for repo in targets]
