from __future__ import annotations

import time
from pathlib import Path

from orch.core import query
from orch.core.constants import STATUSES
from orch.core.fsutil import atomic_write_text


def build_index(ws) -> Path:
    entries = query.list_tickets(ws)
    lines = ["<!-- generated by `orch index`; do not edit -->", f"# Tickets — {ws.config['customer'] or ws.root.name}", ""]
    for status in STATUSES:
        group = [e for e in entries if e.status == status]
        lines += [f"## {status} ({len(group)})", ""]
        if not group:
            lines += ["_none_", ""]
            continue
        lines += ["| ID | Title | Type | Priority | Size | External |", "|---|---|---|---|---|---|"]
        for e in group:
            m = e.meta or {}
            rel = e.path.relative_to(ws.tickets_dir).as_posix()
            title = str(m.get("title") or f"⚠ {e.error}").replace("|", "\\|")
            ext = ", ".join(str(x.get("key")) for x in m.get("external") or [] if isinstance(x, dict))
            lines.append(f"| [{e.id}]({rel}) | {title} | {m.get('type', '')} | {m.get('priority', '')} | {m.get('size', '')} | {ext} |")
        lines.append("")
    out = ws.tickets_dir / "INDEX.md"
    atomic_write_text(out, "\n".join(lines))
    return out


RUN_SCRIPT_MAX_AGE = 86400  # Start agent's .command scripts in state_dir/run/ live one day


def _tidy_run_scripts(ws, now_ts: float) -> list[Path]:
    run = ws.state_dir / "run"
    if not run.is_dir():
        return []
    removed = []
    for p in sorted(run.glob("*.command")):
        if p.is_file() and p.stat().st_mtime < now_ts - RUN_SCRIPT_MAX_AGE:
            p.unlink()
            removed.append(p)
    return removed


def tidy(ws, *, max_age_days: int | None = None, now_ts: float | None = None) -> list[Path]:
    days = max_age_days or ws.config["temporary"]["max_age_days"]
    at = now_ts if now_ts is not None else time.time()
    cutoff = at - days * 86400
    removed: list[Path] = _tidy_run_scripts(ws, at)
    emptied: set[Path] = set()
    base = ws.temporary_dir
    if not base.is_dir():
        return removed
    for p in sorted(base.rglob("*"), key=lambda x: len(x.parts), reverse=True):  # deepest first
        if p.is_file() and p.stat().st_mtime < cutoff:
            p.unlink()
            removed.append(p)
            emptied.add(p.parent)
        elif p.is_dir() and not any(p.iterdir()) and (p in emptied or p.stat().st_mtime < cutoff):
            p.rmdir()
            emptied.add(p.parent)
    return removed
