"""Generator for ``src/orch/canon/_unicode16.py`` (the bundled Unicode 16.0 data).

Run on a Python whose ``unicodedata.unidata_version`` is ``16.0.0`` (3.14 ships it)::

    uv run python tests/canon/gen_unicode16.py > src/orch/canon/_unicode16.py

``tests/canon/test_unicode16.py`` regenerates the data on such a runtime and compares it with the checked-in
module, so the module cannot drift from the generator. The module is data only; the algorithms live in
``orch.canon.text``.
"""

from __future__ import annotations

import sys
import unicodedata

MAX = 0x110000
Q = '"' * 3
HANGUL_S, HANGUL_E = 0xAC00, 0xD7A3


def _ranges(pred) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(MAX):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def generate() -> str:
    if unicodedata.unidata_version != "16.0.0":
        raise SystemExit(f"need Unicode 16.0.0, this runtime has {unicodedata.unidata_version}")
    assigned = _ranges(lambda cp: unicodedata.category(chr(cp)) != "Cn")
    cf = _ranges(lambda cp: unicodedata.category(chr(cp)) == "Cf")
    ccc: list[tuple[int, int, int]] = []
    for cp in range(MAX):
        c = unicodedata.combining(chr(cp))
        if c:
            if ccc and ccc[-1][1] == cp - 1 and ccc[-1][2] == c:
                ccc[-1] = (ccc[-1][0], cp, c)
            else:
                ccc.append((cp, cp, c))
    decomp: list[tuple[int, list[int]]] = []
    compose: list[int] = []
    for cp in range(MAX):
        if HANGUL_S <= cp <= HANGUL_E:
            continue
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        parts = [int(x, 16) for x in d.split()]
        decomp.append((cp, parts))
        if len(parts) == 2 and unicodedata.normalize("NFC", chr(cp)) == chr(cp):
            compose.append(cp)
    lines = [
        '"""Unicode 16.0.0 data bundled for orch.canon.text (generated, do not edit).',
        "",
        "Generated by tests/canon/gen_unicode16.py from a Python with unicodedata.unidata_version 16.0.0.",
        "ticket-format section 11.3 pins Unicode 16.0 for NFC and for 'unassigned', whatever the runtime ships.",
        "",
        "ASSIGNED_RANGES: code points whose General_Category is not Cn (Cs and Co count as assigned).",
        "CF_RANGES: code points whose General_Category is Cf (format characters, bidi controls among them).",
        "CCC_RANGES: canonical combining classes other than 0.",
        "DECOMP: canonical (non-compatibility) single-step decompositions, Hangul syllables excluded.",
        "COMPOSABLE: the primary composites (two-character decomposition, not composition-excluded).",
        '"""',
        "",
        'UNICODE_VERSION = "16.0.0"',
        "",
        'ASSIGNED_RANGES = """',
    ]
    lines += [f"{a:X} {b:X}" for a, b in assigned]
    lines += [Q, "", 'CF_RANGES = """']
    lines += [f"{a:X} {b:X}" for a, b in cf]
    lines += [Q, "", 'CCC_RANGES = """']
    lines += [f"{a:X} {b:X} {c}" for a, b, c in ccc]
    lines += [Q, "", 'DECOMP = """']
    lines += [f"{cp:X} " + " ".join(f"{p:X}" for p in parts) for cp, parts in decomp]
    lines += [Q, "", 'COMPOSABLE = """']
    lines += [f"{cp:X}" for cp in compose]
    lines += [Q, ""]
    return "\n".join(lines)


if __name__ == "__main__":
    sys.stdout.write(generate())
